// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.MainModule.Application.Features.ShipmentLocation;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentLocation;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.Infrastructure.Web.Helpers;
using QuickCode.Freytz.Application.Contracts;

namespace QuickCode.Freytz.MainModule.Application.Tests.Features.ShipmentLocation
{
    public class InsertShipmentLocationCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<IShipmentLocationRepository> _repositoryMock;
        private readonly Mock<ILogger<InsertShipmentLocationCommand.InsertShipmentLocationHandler>> _loggerMock;
        public InsertShipmentLocationCommandTests()
        {
            _repositoryMock = new Mock<IShipmentLocationRepository>();
            _loggerMock = new Mock<ILogger<InsertShipmentLocationCommand.InsertShipmentLocationHandler>>();
        }

        [Fact]
        public async Task Handle_Should_Return_Success_When_Valid_Command()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<ShipmentLocationDto>("tr");
            var fakeResponse = new RepoResponse<ShipmentLocationDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<ShipmentLocationDto>())).ReturnsAsync(fakeResponse);
            var handler = new InsertShipmentLocationCommand.InsertShipmentLocationHandler(_loggerMock.Object, _repositoryMock.Object);
            var command = new InsertShipmentLocationCommand(fakeDto);
            // Act
            var result = await handler.Handle(command, CancellationToken.None);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.InsertAsync(It.IsAny<ShipmentLocationDto>()), Times.Once);
        }

        [Fact]
        public async Task Handle_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<ShipmentLocationDto>("tr");
            var fakeResponse = new RepoResponse<ShipmentLocationDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<ShipmentLocationDto>())).ReturnsAsync(fakeResponse);
            var handler = new InsertShipmentLocationCommand.InsertShipmentLocationHandler(_loggerMock.Object, _repositoryMock.Object);
            var command = new InsertShipmentLocationCommand(fakeDto);
            // Act
            var result = await handler.Handle(command, CancellationToken.None);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}