-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[PRICE_MATRICES]
SET
    [RANGE_PRICE] = @PRM_PRICE_MATRIX_RANGE_PRICE,
    [ROUND_TRIP_PRICE] = @PRM_PRICE_MATRIX_ROUND_TRIP_PRICE,
    [RANGE_END] = @PRM_PRICE_MATRIX_RANGE_END,
    [STATE_ID] = @PRM_PRICE_MATRIX_STATE_ID,
    [VEHICLE_TYPE_ID] = @PRM_PRICE_MATRIX_VEHICLE_TYPE_ID
WHERE
    [ID] = @PRM_PRICE_MATRIX_ID
    AND [IsDeleted] = 0;