-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [GSM_NUMBER],
    [USER_SMS_CODE],
    [SMS_OTP_ID],
    [TRY_COUNT],
    [RESULT]
FROM [dbo].[SM_OTP_VALIDATIONS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;