// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Dtos.VehicleType
{
    public record VehicleTypeDto
    {
        public int Id { get; init; }
        public string Name { get; init; }
        public int Capacity { get; init; }
        public bool IsDeleted { get; init; }
        public int Order { get; init; }
        public string ImagePath { get; init; }
    }
}