// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.ShipmentLocation
{
    public class DeleteItemShipmentLocationCommand : IRequest<Response<bool>>
    {
        public int Id { get; set; }

        public DeleteItemShipmentLocationCommand(int id)
        {
            this.Id = id;
        }

        public class DeleteItemShipmentLocationHandler : IRequestHandler<DeleteItemShipmentLocationCommand, Response<bool>>
        {
            private readonly ILogger<DeleteItemShipmentLocationHandler> _logger;
            private readonly IShipmentLocationRepository _repository;
            public DeleteItemShipmentLocationHandler(ILogger<DeleteItemShipmentLocationHandler> logger, IShipmentLocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(DeleteItemShipmentLocationCommand request, CancellationToken cancellationToken)
            {
                var deleteItem = await _repository.GetByPkAsync(request.Id);
                if (deleteItem.Code == 404)
                    return Response<bool>.NotFound();
                var returnValue = await _repository.DeleteAsync(deleteItem.Value);
                return returnValue.ToResponse();
            }
        }
    }
}