// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.ShipmentLocation
{
    public class UpdateShipmentLocationCommand : IRequest<Response<bool>>
    {
        public int Id { get; set; }
        public ShipmentLocationDto request { get; set; }

        public UpdateShipmentLocationCommand(int id, ShipmentLocationDto request)
        {
            this.request = request;
            this.Id = id;
        }

        public class UpdateShipmentLocationHandler : IRequestHandler<UpdateShipmentLocationCommand, Response<bool>>
        {
            private readonly ILogger<UpdateShipmentLocationHandler> _logger;
            private readonly IShipmentLocationRepository _repository;
            public UpdateShipmentLocationHandler(ILogger<UpdateShipmentLocationHandler> logger, IShipmentLocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(UpdateShipmentLocationCommand request, CancellationToken cancellationToken)
            {
                var updateItem = await _repository.GetByPkAsync(request.Id);
                if (updateItem.Code == 404)
                    return Response<bool>.NotFound();
                var model = request.request;
                var returnValue = await _repository.UpdateAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}