// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Freytz.MainModule.Application.Dtos.DriverPayment;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories;
internal static class DriverPaymentCrudSqlBindings
{
    public const string StoreTableName = "DRIVER_PAYMENTS";
    public const string ParameterNamePrefix = "DRIVER_PAYMENT";
    public const string IdParameterName = "PRM_DRIVER_PAYMENT_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByDateRange = "GetByDateRange";
        public const string GetByDriver = "GetByDriver";
        public const string GetByPk = "GetByPk";
        public const string GetByUser = "GetByUser";
        public const string GetDriverPayments = "GetDriverPayments";
        public const string GetDriverPaymentsDetails = "GetDriverPaymentsDetails";
        public const string GetDriverTotal = "GetDriverTotal";
        public const string GetMonthlySummary = "GetMonthlySummary";
        public const string GetRecent = "GetRecent";
        public const string GetWithDriver = "GetWithDriver";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
        public const string UpdateDescription = "UpdateDescription";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("DRIVER_ID", nameof(DriverPaymentDto.DriverId)),
        ("PAYMENT_ACCOUNT", nameof(DriverPaymentDto.PaymentAccount)),
        ("PAYMENT_AMOUNT", nameof(DriverPaymentDto.PaymentAmount)),
        ("PAYMENT_DATE", nameof(DriverPaymentDto.PaymentDate)),
        ("PAYMENT_DESCRIPTION", nameof(DriverPaymentDto.PaymentDescription)),
        ("USER_ID", nameof(DriverPaymentDto.UserId))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("DRIVER_ID", nameof(DriverPaymentDto.DriverId)),
        ("PAYMENT_ACCOUNT", nameof(DriverPaymentDto.PaymentAccount)),
        ("PAYMENT_AMOUNT", nameof(DriverPaymentDto.PaymentAmount)),
        ("PAYMENT_DATE", nameof(DriverPaymentDto.PaymentDate)),
        ("PAYMENT_DESCRIPTION", nameof(DriverPaymentDto.PaymentDescription)),
        ("USER_ID", nameof(DriverPaymentDto.UserId)),
        ("ID", nameof(DriverPaymentDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(DriverPaymentDto.Id))
    };
}