// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Shipment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Shipment
{
    public class GetDriverShipmentsHistoryQuery : IRequest<Response<List<GetDriverShipmentsHistoryResponseDto>>>
    {
        public int ShipmentDriverId { get; set; }
        public DateTime ShipmentCreateDateFrom { get; set; }
        public DateTime ShipmentCreateDateTo { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetDriverShipmentsHistoryQuery(int shipmentDriverId, DateTime shipmentCreateDateFrom, DateTime shipmentCreateDateTo, int? pageNumber, int? pageSize)
        {
            this.ShipmentDriverId = shipmentDriverId;
            this.ShipmentCreateDateFrom = shipmentCreateDateFrom;
            this.ShipmentCreateDateTo = shipmentCreateDateTo;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetDriverShipmentsHistoryHandler : IRequestHandler<GetDriverShipmentsHistoryQuery, Response<List<GetDriverShipmentsHistoryResponseDto>>>
        {
            private readonly ILogger<GetDriverShipmentsHistoryHandler> _logger;
            private readonly IShipmentRepository _repository;
            public GetDriverShipmentsHistoryHandler(ILogger<GetDriverShipmentsHistoryHandler> logger, IShipmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetDriverShipmentsHistoryResponseDto>>> Handle(GetDriverShipmentsHistoryQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetDriverShipmentsHistoryAsync(request.ShipmentDriverId, request.ShipmentCreateDateFrom, request.ShipmentCreateDateTo, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}