// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Shipment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Shipment
{
    public class GetDriverShipmentsQuery : IRequest<Response<List<GetDriverShipmentsResponseDto>>>
    {
        public int ShipmentDriverId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetDriverShipmentsQuery(int shipmentDriverId, int? pageNumber, int? pageSize)
        {
            this.ShipmentDriverId = shipmentDriverId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetDriverShipmentsHandler : IRequestHandler<GetDriverShipmentsQuery, Response<List<GetDriverShipmentsResponseDto>>>
        {
            private readonly ILogger<GetDriverShipmentsHandler> _logger;
            private readonly IShipmentRepository _repository;
            public GetDriverShipmentsHandler(ILogger<GetDriverShipmentsHandler> logger, IShipmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetDriverShipmentsResponseDto>>> Handle(GetDriverShipmentsQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetDriverShipmentsAsync(request.ShipmentDriverId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}