-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT PM.[ID] AS PRICE_MATRIX_ID,
	PM.[RANGE_PRICE], PM.[RANGE_END], S.[NAME] AS STATE_NAME 
FROM [PRICE_MATRICES] PM 
	INNER JOIN [STATES] S 
			ON PM.[STATE_ID] = S.[ID] 
WHERE PM.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND PM.[STATE_ID] = @PRM_PRICE_MATRICES_STATE_ID 
	AND S.[ID] = @PRM_STATES_ID 
ORDER BY PM.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 