// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Freytz.MainModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class PriceMatrix
    {
        public static class Query
        {
            private const string _prefix = "MainModule.PriceMatrix.Query";
            private const string _sqlScriptStem = "PriceMatrix";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string CalculatePrice => ResourceKey($"{_sqlScriptStem}.CalculatePrice.g.sql");
            public static string GetByState => ResourceKey($"{_sqlScriptStem}.GetByState.g.sql");
            public static string GetByVehicleType => ResourceKey($"{_sqlScriptStem}.GetByVehicleType.g.sql");
            public static string GetByStateAndVehicle => ResourceKey($"{_sqlScriptStem}.GetByStateAndVehicle.g.sql");
            public static string GetWithState => ResourceKey($"{_sqlScriptStem}.GetWithState.g.sql");
            public static string GetWithVehicleType => ResourceKey($"{_sqlScriptStem}.GetWithVehicleType.g.sql");
        }
    }
}