// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.IdentityModule.Domain.Entities;
using QuickCode.Freytz.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.IdentityModule.Application.Dtos.AuditLog;
using QuickCode.Freytz.IdentityModule.Domain.Enums;

namespace QuickCode.Freytz.IdentityModule.Application.Features.AuditLog
{
    public class StatsMonthlyHttpRequestsQuery : IRequest<Response<StatsMonthlyHttpRequestsResponseDto>>
    {
        public StatsMonthlyHttpRequestsQuery()
        {
        }

        public class StatsMonthlyHttpRequestsHandler : IRequestHandler<StatsMonthlyHttpRequestsQuery, Response<StatsMonthlyHttpRequestsResponseDto>>
        {
            private readonly ILogger<StatsMonthlyHttpRequestsHandler> _logger;
            private readonly IAuditLogRepository _repository;
            public StatsMonthlyHttpRequestsHandler(ILogger<StatsMonthlyHttpRequestsHandler> logger, IAuditLogRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<StatsMonthlyHttpRequestsResponseDto>> Handle(StatsMonthlyHttpRequestsQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.StatsMonthlyHttpRequestsAsync();
                return returnValue.ToResponse();
            }
        }
    }
}