// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Freytz.MainModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Payment
    {
        public static class Query
        {
            private const string _prefix = "MainModule.Payment.Query";
            private const string _sqlScriptStem = "Payment";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetByStatus => ResourceKey($"{_sqlScriptStem}.GetByStatus.g.sql");
            public static string GetByType => ResourceKey($"{_sqlScriptStem}.GetByType.g.sql");
            public static string GetPending => ResourceKey($"{_sqlScriptStem}.GetPending.g.sql");
            public static string GetByCreditCard => ResourceKey($"{_sqlScriptStem}.GetByCreditCard.g.sql");
            public static string GetByDateRange => ResourceKey($"{_sqlScriptStem}.GetByDateRange.g.sql");
            public static string GetRecent => ResourceKey($"{_sqlScriptStem}.GetRecent.g.sql");
            public static string GetDailySummary => ResourceKey($"{_sqlScriptStem}.GetDailySummary.g.sql");
            public static string GetMonthlySummary => ResourceKey($"{_sqlScriptStem}.GetMonthlySummary.g.sql");
            public static string GetCapturedCount => ResourceKey($"{_sqlScriptStem}.GetCapturedCount.g.sql");
        }
    }
}