-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT P.[ID], P.[PAYMENT_TYPE], P.[PAYMENT_STATUS], P.[PAYMENT_TIME], P.[AMOUNT], P.[TOTAL_AMOUNT] 
FROM [PAYMENTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[PAYMENT_TYPE] = @PRM_PAYMENT_PAYMENT_TYPE 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 