-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[SHIPMENT_PACKAGES]
SET
    [SHIPMENT_ID] = @PRM_SHIPMENT_PACKAGE_SHIPMENT_ID,
    [PACKAGE_PHOTO] = @PRM_SHIPMENT_PACKAGE_PACKAGE_PHOTO,
    [PACKAGE_DESCRIPTION] = @PRM_SHIPMENT_PACKAGE_PACKAGE_DESCRIPTION,
    [RECIPIENT_ID] = @PRM_SHIPMENT_PACKAGE_RECIPIENT_ID,
    [SENDER_ID] = @PRM_SHIPMENT_PACKAGE_SENDER_ID
WHERE
    [ID] = @PRM_SHIPMENT_PACKAGE_ID
    AND [IsDeleted] = 0;