// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Payment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Payment
{
    public class GetPendingQuery : IRequest<Response<List<GetPendingResponseDto>>>
    {
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetPendingQuery(int? pageNumber, int? pageSize)
        {
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetPendingHandler : IRequestHandler<GetPendingQuery, Response<List<GetPendingResponseDto>>>
        {
            private readonly ILogger<GetPendingHandler> _logger;
            private readonly IPaymentRepository _repository;
            public GetPendingHandler(ILogger<GetPendingHandler> logger, IPaymentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetPendingResponseDto>>> Handle(GetPendingQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetPendingAsync(request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}