// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.SmInfo;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.SmInfo
{
    public class InsertSmInfoCommand : IRequest<Response<SmInfoDto>>
    {
        public SmInfoDto request { get; set; }

        public InsertSmInfoCommand(SmInfoDto request)
        {
            this.request = request;
        }

        public class InsertSmInfoHandler : IRequestHandler<InsertSmInfoCommand, Response<SmInfoDto>>
        {
            private readonly ILogger<InsertSmInfoHandler> _logger;
            private readonly ISmInfoRepository _repository;
            public InsertSmInfoHandler(ILogger<InsertSmInfoHandler> logger, ISmInfoRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<SmInfoDto>> Handle(InsertSmInfoCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.InsertAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}