-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT SP.[ID], SP.[SHIPMENT_ID], SP.[PACKAGE_DESCRIPTION], SP.[RECIPIENT_ID], SP.[SENDER_ID] 
FROM [SHIPMENT_PACKAGES] SP 
WHERE SP.[IsDeleted] = 0 
	AND SP.[SENDER_ID] = @PRM_SHIPMENT_PACKAGE_SENDER_ID 
ORDER BY SP.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 