-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT SP.[ID] AS PACKAGE_ID,
	SP.[PACKAGE_DESCRIPTION], SH.[CREATE_DATE] AS SHIPMENT_CREATE_DATE,
	SH.[SHIPMENT_STATUS] 
FROM [SHIPMENT_PACKAGES] SP 
	INNER JOIN [SHIPMENTS] SH 
			ON SP.[SHIPMENT_ID] = SH.[ID] 
WHERE SP.[IsDeleted] = 0 
	AND SH.[IsDeleted] = 0 
	AND SP.[SHIPMENT_ID] = @PRM_SHIPMENT_PACKAGES_SHIPMENT_ID 
	AND SH.[ID] = @PRM_SHIPMENTS_ID 
ORDER BY SP.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 