// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Data;
using QuickCode.Freytz.Infrastructure.Data.Extensions;
using QuickCode.Freytz.Infrastructure.Data.Helpers;
using QuickCode.Freytz.MainModule.Application.Dtos.Customer;
using QuickCode.Freytz.MainModule.Application.Mappings;
using QuickCode.Freytz.MainModule.Persistence.Sql;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories
{
    public partial class CustomerRepository : BaseRepository, ICustomerRepository
    {
        public async Task<RepoResponse<int>> UpdateStatusAsync(int customerId, UpdateStatusRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.UpdateStatus, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.UpdateStatus);
                var parameters = new
                {
                    CUSTOMER_STATUS = updateRequest.CustomerStatus,
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> ActivateAsync(int customerId, ActivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.Activate, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.Activate);
                var parameters = new
                {
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> DeactivateAsync(int customerId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.Deactivate, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.Deactivate);
                var parameters = new
                {
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdateDeviceAsync(int customerId, UpdateDeviceRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.UpdateDevice, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.UpdateDevice);
                var parameters = new
                {
                    CUSTOMER_DEVICE_TYPE = updateRequest.CustomerDeviceType,
                    CUSTOMER_DEVICE_ID = updateRequest.CustomerDeviceId,
                    CUSTOMER_FIREBASE_ID = updateRequest.CustomerFirebaseId,
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdateFirebaseIdAsync(int customerId, UpdateFirebaseIdRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.UpdateFirebaseId, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.UpdateFirebaseId);
                var parameters = new
                {
                    CUSTOMER_FIREBASE_ID = updateRequest.CustomerFirebaseId,
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdatePasswordAsync(int customerId, UpdatePasswordRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.UpdatePassword, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.UpdatePassword);
                var parameters = new
                {
                    CUSTOMER_PASSWORD = updateRequest.CustomerPassword,
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdateProfileAsync(int customerId, UpdateProfileRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.UpdateProfile, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.UpdateProfile);
                var parameters = new
                {
                    CUSTOMER_NAME = updateRequest.CustomerName,
                    CUSTOMER_SURNAME = updateRequest.CustomerSurname,
                    CUSTOMER_EMAIL = updateRequest.CustomerEmail,
                    CUSTOMER_GSM = updateRequest.CustomerGsm,
                    CUSTOMER_PHOTO = updateRequest.CustomerPhoto,
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdateProfileIdAsync(int customerId, UpdateProfileIdRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.UpdateProfileId, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.UpdateProfileId);
                var parameters = new
                {
                    CUSTOMER_PROFILE_ID = updateRequest.CustomerProfileId,
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}