// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Data;
using QuickCode.Freytz.Infrastructure.Data.Extensions;
using QuickCode.Freytz.Infrastructure.Data.Helpers;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentPackage;
using QuickCode.Freytz.MainModule.Application.Mappings;
using QuickCode.Freytz.MainModule.Persistence.Sql;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories
{
    public partial class ShipmentPackageRepository : BaseRepository, IShipmentPackageRepository
    {
        public async Task<RepoResponse<GetPackagePhotoResponseDto>> GetPackagePhotoAsync(int shipmentPackageId, int shipmentPackageShipmentId)
        {
            return await ExecuteWithExceptionHandling(ShipmentPackageCrudSqlBindings.OperationNames.GetPackagePhoto, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ShipmentPackage.Query.GetPackagePhoto);
                var parameters = new
                {
                    PRM_SHIPMENT_PACKAGE_SHIPMENT_ID = shipmentPackageShipmentId,
                    PRM_SHIPMENT_PACKAGE_ID = shipmentPackageId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetPackagePhotoResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ShipmentPackage");
            });
        }

        public async Task<RepoResponse<List<GetByShipmentResponseDto>>> GetByShipmentAsync(int shipmentPackageShipmentId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(ShipmentPackageCrudSqlBindings.OperationNames.GetByShipment, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByShipmentResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ShipmentPackage.Query.GetByShipment);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SHIPMENT_PACKAGE_SHIPMENT_ID = shipmentPackageShipmentId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByShipmentResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ShipmentPackage");
                }
            });
        }

        public async Task<RepoResponse<List<GetByRecipientResponseDto>>> GetByRecipientAsync(int shipmentPackageRecipientId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(ShipmentPackageCrudSqlBindings.OperationNames.GetByRecipient, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByRecipientResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ShipmentPackage.Query.GetByRecipient);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SHIPMENT_PACKAGE_RECIPIENT_ID = shipmentPackageRecipientId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByRecipientResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ShipmentPackage");
                }
            });
        }

        public async Task<RepoResponse<List<GetBySenderResponseDto>>> GetBySenderAsync(int shipmentPackageSenderId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(ShipmentPackageCrudSqlBindings.OperationNames.GetBySender, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetBySenderResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ShipmentPackage.Query.GetBySender);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SHIPMENT_PACKAGE_SENDER_ID = shipmentPackageSenderId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetBySenderResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ShipmentPackage");
                }
            });
        }

        public async Task<RepoResponse<List<GetWithRecipientResponseDto>>> GetWithRecipientAsync(int shipmentPackagesRecipientId, int recipientsId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(ShipmentPackageCrudSqlBindings.OperationNames.GetWithRecipient, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetWithRecipientResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ShipmentPackage.Query.GetWithRecipient);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SHIPMENT_PACKAGES_RECIPIENT_ID = shipmentPackagesRecipientId,
                        PRM_RECIPIENTS_ID = recipientsId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetWithRecipientResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ShipmentPackage");
                }
            });
        }

        public async Task<RepoResponse<List<GetWithSenderResponseDto>>> GetWithSenderAsync(int shipmentPackagesSenderId, int sendersId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(ShipmentPackageCrudSqlBindings.OperationNames.GetWithSender, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetWithSenderResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ShipmentPackage.Query.GetWithSender);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SHIPMENT_PACKAGES_SENDER_ID = shipmentPackagesSenderId,
                        PRM_SENDERS_ID = shipmentPackagesSenderId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetWithSenderResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ShipmentPackage");
                }
            });
        }

        public async Task<RepoResponse<List<GetWithShipmentResponseDto>>> GetWithShipmentAsync(int shipmentPackagesShipmentId, int shipmentsId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(ShipmentPackageCrudSqlBindings.OperationNames.GetWithShipment, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetWithShipmentResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ShipmentPackage.Query.GetWithShipment);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SHIPMENT_PACKAGES_SHIPMENT_ID = shipmentPackagesShipmentId,
                        PRM_SHIPMENTS_ID = shipmentPackagesShipmentId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetWithShipmentResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ShipmentPackage");
                }
            });
        }
    }
}