// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverCommission;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverCommission
{
    public class GetItemDriverCommissionQuery : IRequest<Response<DriverCommissionDto>>
    {
        public int Id { get; set; }

        public GetItemDriverCommissionQuery(int id)
        {
            this.Id = id;
        }

        public class GetItemDriverCommissionHandler : IRequestHandler<GetItemDriverCommissionQuery, Response<DriverCommissionDto>>
        {
            private readonly ILogger<GetItemDriverCommissionHandler> _logger;
            private readonly IDriverCommissionRepository _repository;
            public GetItemDriverCommissionHandler(ILogger<GetItemDriverCommissionHandler> logger, IDriverCommissionRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<DriverCommissionDto>> Handle(GetItemDriverCommissionQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.Id);
                return returnValue.ToResponse();
            }
        }
    }
}