-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [PAYMENTS] 
	SET [PAYMENT_STATUS] = @PAYMENT_PAYMENT_STATUS 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_PAYMENT_ID