// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverPaymentShipment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverPaymentShipment
{
    public class InsertDriverPaymentShipmentCommand : IRequest<Response<DriverPaymentShipmentDto>>
    {
        public DriverPaymentShipmentDto request { get; set; }

        public InsertDriverPaymentShipmentCommand(DriverPaymentShipmentDto request)
        {
            this.request = request;
        }

        public class InsertDriverPaymentShipmentHandler : IRequestHandler<InsertDriverPaymentShipmentCommand, Response<DriverPaymentShipmentDto>>
        {
            private readonly ILogger<InsertDriverPaymentShipmentHandler> _logger;
            private readonly IDriverPaymentShipmentRepository _repository;
            public InsertDriverPaymentShipmentHandler(ILogger<InsertDriverPaymentShipmentHandler> logger, IDriverPaymentShipmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<DriverPaymentShipmentDto>> Handle(InsertDriverPaymentShipmentCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.InsertAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}