// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverPaymentShipment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverPaymentShipment
{
    public class UpdateDriverPaymentShipmentCommand : IRequest<Response<bool>>
    {
        public int DriverPaymentId { get; set; }
        public int ShipmentId { get; set; }
        public DriverPaymentShipmentDto request { get; set; }

        public UpdateDriverPaymentShipmentCommand(int driverPaymentId, int shipmentId, DriverPaymentShipmentDto request)
        {
            this.request = request;
            this.DriverPaymentId = driverPaymentId;
            this.ShipmentId = shipmentId;
        }

        public class UpdateDriverPaymentShipmentHandler : IRequestHandler<UpdateDriverPaymentShipmentCommand, Response<bool>>
        {
            private readonly ILogger<UpdateDriverPaymentShipmentHandler> _logger;
            private readonly IDriverPaymentShipmentRepository _repository;
            public UpdateDriverPaymentShipmentHandler(ILogger<UpdateDriverPaymentShipmentHandler> logger, IDriverPaymentShipmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(UpdateDriverPaymentShipmentCommand request, CancellationToken cancellationToken)
            {
                var updateItem = await _repository.GetByPkAsync(request.DriverPaymentId, request.ShipmentId);
                if (updateItem.Code == 404)
                    return Response<bool>.NotFound();
                var model = request.request;
                var returnValue = await _repository.UpdateAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}