// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Dtos.SmOtpValidation
{
    public record GetWithOtpResponseDto
    {
        public int ValidationId { get; init; }
        public string ValidationGsm { get; init; }
        public int TryCount { get; init; }
        public OtpValidationResult Result { get; init; }
        public string OtpCode { get; init; }
        public DateTime OtpDate { get; init; }
    }
}