// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverLocation
{
    public class GetItemDriverLocationQuery : IRequest<Response<DriverLocationDto>>
    {
        public int Id { get; set; }

        public GetItemDriverLocationQuery(int id)
        {
            this.Id = id;
        }

        public class GetItemDriverLocationHandler : IRequestHandler<GetItemDriverLocationQuery, Response<DriverLocationDto>>
        {
            private readonly ILogger<GetItemDriverLocationHandler> _logger;
            private readonly IDriverLocationRepository _repository;
            public GetItemDriverLocationHandler(ILogger<GetItemDriverLocationHandler> logger, IDriverLocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<DriverLocationDto>> Handle(GetItemDriverLocationQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.Id);
                return returnValue.ToResponse();
            }
        }
    }
}