// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverLocation
{
    public class GetLatestByDriverQuery : IRequest<Response<GetLatestByDriverResponseDto>>
    {
        public int DriverLocationDriverId { get; set; }

        public GetLatestByDriverQuery(int driverLocationDriverId)
        {
            this.DriverLocationDriverId = driverLocationDriverId;
        }

        public class GetLatestByDriverHandler : IRequestHandler<GetLatestByDriverQuery, Response<GetLatestByDriverResponseDto>>
        {
            private readonly ILogger<GetLatestByDriverHandler> _logger;
            private readonly IDriverLocationRepository _repository;
            public GetLatestByDriverHandler(ILogger<GetLatestByDriverHandler> logger, IDriverLocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<GetLatestByDriverResponseDto>> Handle(GetLatestByDriverQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetLatestByDriverAsync(request.DriverLocationDriverId);
                return returnValue.ToResponse();
            }
        }
    }
}