// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverLocation
{
    public class GetRecentByDriverQuery : IRequest<Response<List<GetRecentByDriverResponseDto>>>
    {
        public int DriverLocationDriverId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetRecentByDriverQuery(int driverLocationDriverId, int? pageNumber, int? pageSize)
        {
            this.DriverLocationDriverId = driverLocationDriverId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetRecentByDriverHandler : IRequestHandler<GetRecentByDriverQuery, Response<List<GetRecentByDriverResponseDto>>>
        {
            private readonly ILogger<GetRecentByDriverHandler> _logger;
            private readonly IDriverLocationRepository _repository;
            public GetRecentByDriverHandler(ILogger<GetRecentByDriverHandler> logger, IDriverLocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetRecentByDriverResponseDto>>> Handle(GetRecentByDriverQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetRecentByDriverAsync(request.DriverLocationDriverId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}