// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.CustomerLoginAttempt;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.CustomerLoginAttempt
{
    public class DeleteCustomerLoginAttemptCommand : IRequest<Response<bool>>
    {
        public CustomerLoginAttemptDto request { get; set; }

        public DeleteCustomerLoginAttemptCommand(CustomerLoginAttemptDto request)
        {
            this.request = request;
        }

        public class DeleteCustomerLoginAttemptHandler : IRequestHandler<DeleteCustomerLoginAttemptCommand, Response<bool>>
        {
            private readonly ILogger<DeleteCustomerLoginAttemptHandler> _logger;
            private readonly ICustomerLoginAttemptRepository _repository;
            public DeleteCustomerLoginAttemptHandler(ILogger<DeleteCustomerLoginAttemptHandler> logger, ICustomerLoginAttemptRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(DeleteCustomerLoginAttemptCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.DeleteAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}