// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.IdentityModule.Domain.Entities;
using QuickCode.Freytz.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Data;
using QuickCode.Freytz.Infrastructure.Data.Extensions;
using QuickCode.Freytz.Infrastructure.Data.Helpers;
using QuickCode.Freytz.IdentityModule.Application.Dtos.ApiMethodDefinition;
using QuickCode.Freytz.IdentityModule.Application.Mappings;
using QuickCode.Freytz.IdentityModule.Persistence.Sql;
using QuickCode.Freytz.IdentityModule.Domain.Enums;

namespace QuickCode.Freytz.IdentityModule.Persistence.Repositories
{
    public partial class ApiMethodDefinitionRepository : BaseRepository, IApiMethodDefinitionRepository
    {
        public async Task<RepoResponse<int>> DeleteApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionModuleName)
        {
            return await ExecuteWithExceptionHandling(ApiMethodDefinitionCrudSqlBindings.OperationNames.DeleteApiMethodDefinitionsWithModuleName, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Command.DeleteApiMethodDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModuleName = apiMethodDefinitionModuleName
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> DeleteApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionModelName)
        {
            return await ExecuteWithExceptionHandling(ApiMethodDefinitionCrudSqlBindings.OperationNames.DeleteApiMethodDefinitionsWithModelName, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Command.DeleteApiMethodDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModelName = apiMethodDefinitionModelName
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}