-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CLA.[ID], CLA.[CLIENT_IP], CLA.[LOGIN_DATE], CLA.[ATTEMPT_RESULT] 
FROM [CUSTOMER_LOGIN_ATTEMPTS] CLA 
WHERE CLA.[IsDeleted] = 0 
	AND CLA.[CUSTOMER_ID] = @PRM_CUSTOMER_LOGIN_ATTEMPT_CUSTOMER_ID 
	AND CLA.[ATTEMPT_RESULT] = 'FAILED' 
ORDER BY CLA.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 