-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CLA.[ID], CLA.[CUSTOMER_ID], CLA.[CLIENT_IP], CLA.[LOGIN_DATE], CLA.[ATTEMPT_RESULT] 
FROM [CUSTOMER_LOGIN_ATTEMPTS] CLA 
WHERE CLA.[IsDeleted] = 0 
	AND CLA.[LOGIN_DATE] > DATEADD(DAY, -7,
	GETDATE()) 
ORDER BY CLA.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 