-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT COUNT(*) 
FROM [CUSTOMER_LOGIN_ATTEMPTS] CLA 
WHERE CLA.[IsDeleted] = 0 
	AND CLA.[ATTEMPT_RESULT] = 'FAILED' 
	AND CLA.[LOGIN_DATE] > DATEADD(DAY, -1,
	GETDATE()) 
ORDER BY  