-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 D.[ID], D.[MAX_DISTANCE] 
FROM [DRIVERS] D 
WHERE D.[IsDeleted] = 0 
	AND D.[ID] = @PRM_DRIVER_ID 
ORDER BY D.[ID] 