-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CASE WHEN EXISTS (
SELECT 1 
FROM [DRIVERS] D 
WHERE D.[IsDeleted] = 0 
	AND D.[DEVICE_TYPE] = @PRM_DRIVER_DEVICE_TYPE 
	AND D.[DEVICE_ID] = @PRM_DRIVER_DEVICE_ID ) THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END