-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 D.[ID], D.[NAME], D.[SURNAME], D.[EMAIL], D.[GSM], D.[DRIVER_STATUS], D.[STATUS], D.[STATE_ID], D.[VEHICLE_TYPE_ID], D.[DEVICE_TYPE], D.[DEVICE_ID], D.[FIREBASE_ID], D.[MAX_DISTANCE], D.[PHOTO], D.[VEHICLE_PLATE] 
FROM [DRIVERS] D 
WHERE D.[IsDeleted] = 0 
	AND D.[EMAIL] = @PRM_DRIVER_EMAIL 
	AND D.[PASSWORD] = @PRM_DRIVER_PASSWORD 
ORDER BY D.[ID] 