-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT D.[ID] AS DRIVER_ID,
	D.[NAME] AS DRIVER_NAME,
	D.[VEHICLE_TYPE_ID], D.[MAX_DISTANCE], DL.[LATITUDE], DL.[LONGITUDE] 
FROM [DRIVERS] D 
	INNER JOIN [DRIVER_LOCATIONS] DL 
			ON DL.[DRIVER_ID] = D.[ID] 
WHERE D.[IsDeleted] = 0 
	AND DL.[IsDeleted] = 0 
	AND D.[LAST_LOCATION_ID] = @PRM_DRIVERS_LAST_LOCATION_ID 
	AND DL.[ID] = @PRM_DRIVER_LOCATIONS_ID 
	AND D.[DRIVER_STATUS] = 'AVAILABLE' 
	AND D.[STATUS] = 'ACTIVE' 
ORDER BY D.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 