-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[RECIPIENTS]
SET
    [CUSTOMER_ID] = @PRM_RECIPIENT_CUSTOMER_ID,
    [NAME] = @PRM_RECIPIENT_NAME,
    [GSM] = @PRM_RECIPIENT_GSM,
    [EMAIL] = @PRM_RECIPIENT_EMAIL,
    [INSTRUCTIONS] = @PRM_RECIPIENT_INSTRUCTIONS,
    [IS_STORED] = @PRM_RECIPIENT_IS_STORED
WHERE
    [ID] = @PRM_RECIPIENT_ID
    AND [IsDeleted] = 0;