// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Data;
using QuickCode.Freytz.Infrastructure.Data.Extensions;
using QuickCode.Freytz.Infrastructure.Data.Helpers;
using QuickCode.Freytz.MainModule.Application.Dtos.Payment;
using QuickCode.Freytz.MainModule.Application.Mappings;
using QuickCode.Freytz.MainModule.Persistence.Sql;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories
{
    public partial class PaymentRepository : BaseRepository, IPaymentRepository
    {
        public async Task<RepoResponse<int>> UpdateStatusAsync(int paymentId, UpdateStatusRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(PaymentCrudSqlBindings.OperationNames.UpdateStatus, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Payment.Command.UpdateStatus);
                var parameters = new
                {
                    PAYMENT_PAYMENT_STATUS = updateRequest.PaymentPaymentStatus,
                    PRM_PAYMENT_ID = paymentId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> MarkCapturedAsync(int paymentId, MarkCapturedRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(PaymentCrudSqlBindings.OperationNames.MarkCaptured, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Payment.Command.MarkCaptured);
                var parameters = new
                {
                    PAYMENT_CAPTURED_AMOUNT = updateRequest.PaymentCapturedAmount,
                    PAYMENT_CC_REF_NO = updateRequest.PaymentCcRefNo,
                    PRM_PAYMENT_ID = paymentId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> MarkFailedAsync(int paymentId, MarkFailedRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(PaymentCrudSqlBindings.OperationNames.MarkFailed, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Payment.Command.MarkFailed);
                var parameters = new
                {
                    PRM_PAYMENT_ID = paymentId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> SetPaymentRefAsync(int paymentId, SetPaymentRefRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(PaymentCrudSqlBindings.OperationNames.SetPaymentRef, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Payment.Command.SetPaymentRef);
                var parameters = new
                {
                    PAYMENT_PAYMENT_REF = updateRequest.PaymentPaymentRef,
                    PRM_PAYMENT_ID = paymentId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}