// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Freytz.MainModule.Application.Dtos.Payment;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories;
internal static class PaymentCrudSqlBindings
{
    public const string StoreTableName = "PAYMENTS";
    public const string ParameterNamePrefix = "PAYMENT";
    public const string IdParameterName = "PRM_PAYMENT_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByCreditCard = "GetByCreditCard";
        public const string GetByDateRange = "GetByDateRange";
        public const string GetByPk = "GetByPk";
        public const string GetByStatus = "GetByStatus";
        public const string GetByType = "GetByType";
        public const string GetCapturedCount = "GetCapturedCount";
        public const string GetDailySummary = "GetDailySummary";
        public const string GetMonthlySummary = "GetMonthlySummary";
        public const string GetPending = "GetPending";
        public const string GetRecent = "GetRecent";
        public const string Insert = "Insert";
        public const string MarkCaptured = "MarkCaptured";
        public const string MarkFailed = "MarkFailed";
        public const string Select = "Select";
        public const string SetPaymentRef = "SetPaymentRef";
        public const string Update = "Update";
        public const string UpdateStatus = "UpdateStatus";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("PAYMENT_TYPE", nameof(PaymentDto.PaymentType)),
        ("PAYMENT_STATUS", nameof(PaymentDto.PaymentStatus)),
        ("PAYMENT_TIME", nameof(PaymentDto.PaymentTime)),
        ("AMOUNT", nameof(PaymentDto.Amount)),
        ("TAX_AMOUNT", nameof(PaymentDto.TaxAmount)),
        ("TOTAL_AMOUNT", nameof(PaymentDto.TotalAmount)),
        ("CREDIT_CARD_ID", nameof(PaymentDto.CreditCardId)),
        ("CC_PAYMENT_TIME", nameof(PaymentDto.CcPaymentTime)),
        ("CC_REF_NO", nameof(PaymentDto.CcRefNo)),
        ("PAYMENT_REF", nameof(PaymentDto.PaymentRef)),
        ("CAPTURED_AMOUNT", nameof(PaymentDto.CapturedAmount))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("PAYMENT_TYPE", nameof(PaymentDto.PaymentType)),
        ("PAYMENT_STATUS", nameof(PaymentDto.PaymentStatus)),
        ("PAYMENT_TIME", nameof(PaymentDto.PaymentTime)),
        ("AMOUNT", nameof(PaymentDto.Amount)),
        ("TAX_AMOUNT", nameof(PaymentDto.TaxAmount)),
        ("TOTAL_AMOUNT", nameof(PaymentDto.TotalAmount)),
        ("CREDIT_CARD_ID", nameof(PaymentDto.CreditCardId)),
        ("CC_PAYMENT_TIME", nameof(PaymentDto.CcPaymentTime)),
        ("CC_REF_NO", nameof(PaymentDto.CcRefNo)),
        ("PAYMENT_REF", nameof(PaymentDto.PaymentRef)),
        ("CAPTURED_AMOUNT", nameof(PaymentDto.CapturedAmount)),
        ("ID", nameof(PaymentDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(PaymentDto.Id))
    };
}