// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Payment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Payment
{
    public class InsertPaymentCommand : IRequest<Response<PaymentDto>>
    {
        public PaymentDto request { get; set; }

        public InsertPaymentCommand(PaymentDto request)
        {
            this.request = request;
        }

        public class InsertPaymentHandler : IRequestHandler<InsertPaymentCommand, Response<PaymentDto>>
        {
            private readonly ILogger<InsertPaymentHandler> _logger;
            private readonly IPaymentRepository _repository;
            public InsertPaymentHandler(ILogger<InsertPaymentHandler> logger, IPaymentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<PaymentDto>> Handle(InsertPaymentCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.InsertAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}