// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Payment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Payment
{
    public class SetPaymentRefCommand : IRequest<Response<int>>
    {
        public int PaymentId { get; set; }
        public SetPaymentRefRequestDto UpdateRequest { get; set; }

        public SetPaymentRefCommand(int paymentId, SetPaymentRefRequestDto updateRequest)
        {
            this.PaymentId = paymentId;
            this.UpdateRequest = updateRequest;
        }

        public class SetPaymentRefHandler : IRequestHandler<SetPaymentRefCommand, Response<int>>
        {
            private readonly ILogger<SetPaymentRefHandler> _logger;
            private readonly IPaymentRepository _repository;
            public SetPaymentRefHandler(ILogger<SetPaymentRefHandler> logger, IPaymentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(SetPaymentRefCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.SetPaymentRefAsync(request.PaymentId, request.UpdateRequest);
                return returnValue.ToResponse();
            }
        }
    }
}