// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverPaymentShipment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverPaymentShipment
{
    public class GetItemDriverPaymentShipmentQuery : IRequest<Response<DriverPaymentShipmentDto>>
    {
        public int DriverPaymentId { get; set; }
        public int ShipmentId { get; set; }

        public GetItemDriverPaymentShipmentQuery(int driverPaymentId, int shipmentId)
        {
            this.DriverPaymentId = driverPaymentId;
            this.ShipmentId = shipmentId;
        }

        public class GetItemDriverPaymentShipmentHandler : IRequestHandler<GetItemDriverPaymentShipmentQuery, Response<DriverPaymentShipmentDto>>
        {
            private readonly ILogger<GetItemDriverPaymentShipmentHandler> _logger;
            private readonly IDriverPaymentShipmentRepository _repository;
            public GetItemDriverPaymentShipmentHandler(ILogger<GetItemDriverPaymentShipmentHandler> logger, IDriverPaymentShipmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<DriverPaymentShipmentDto>> Handle(GetItemDriverPaymentShipmentQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.DriverPaymentId, request.ShipmentId);
                return returnValue.ToResponse();
            }
        }
    }
}