// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverPaymentShipment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverPaymentShipment
{
    public class GetWithPaymentQuery : IRequest<Response<List<GetWithPaymentResponseDto>>>
    {
        public int DriverPaymentShipmentsDriverPaymentId { get; set; }
        public int DriverPaymentsId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetWithPaymentQuery(int driverPaymentShipmentsDriverPaymentId, int driverPaymentsId, int? pageNumber, int? pageSize)
        {
            this.DriverPaymentShipmentsDriverPaymentId = driverPaymentShipmentsDriverPaymentId;
            this.DriverPaymentsId = driverPaymentsId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetWithPaymentHandler : IRequestHandler<GetWithPaymentQuery, Response<List<GetWithPaymentResponseDto>>>
        {
            private readonly ILogger<GetWithPaymentHandler> _logger;
            private readonly IDriverPaymentShipmentRepository _repository;
            public GetWithPaymentHandler(ILogger<GetWithPaymentHandler> logger, IDriverPaymentShipmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetWithPaymentResponseDto>>> Handle(GetWithPaymentQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetWithPaymentAsync(request.DriverPaymentShipmentsDriverPaymentId, request.DriverPaymentsId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}