// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.UserState;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.UserState
{
    public class DeleteUserStateCommand : IRequest<Response<bool>>
    {
        public UserStateDto request { get; set; }

        public DeleteUserStateCommand(UserStateDto request)
        {
            this.request = request;
        }

        public class DeleteUserStateHandler : IRequestHandler<DeleteUserStateCommand, Response<bool>>
        {
            private readonly ILogger<DeleteUserStateHandler> _logger;
            private readonly IUserStateRepository _repository;
            public DeleteUserStateHandler(ILogger<DeleteUserStateHandler> logger, IUserStateRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(DeleteUserStateCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.DeleteAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}