// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.CreditCard;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.CreditCard
{
    public class GetItemCreditCardQuery : IRequest<Response<CreditCardDto>>
    {
        public int Id { get; set; }

        public GetItemCreditCardQuery(int id)
        {
            this.Id = id;
        }

        public class GetItemCreditCardHandler : IRequestHandler<GetItemCreditCardQuery, Response<CreditCardDto>>
        {
            private readonly ILogger<GetItemCreditCardHandler> _logger;
            private readonly ICreditCardRepository _repository;
            public GetItemCreditCardHandler(ILogger<GetItemCreditCardHandler> logger, ICreditCardRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<CreditCardDto>> Handle(GetItemCreditCardQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.Id);
                return returnValue.ToResponse();
            }
        }
    }
}