// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.CreditCard;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.CreditCard
{
    public class ListCreditCardQuery : IRequest<Response<List<CreditCardDto>>>
    {
        public int? PageNumber { get; set; }
        public int? PageSize { get; set; }

        public ListCreditCardQuery(int? pageNumber, int? pageSize)
        {
            this.PageNumber = pageNumber;
            this.PageSize = pageSize;
        }

        public class ListCreditCardHandler : IRequestHandler<ListCreditCardQuery, Response<List<CreditCardDto>>>
        {
            private readonly ILogger<ListCreditCardHandler> _logger;
            private readonly ICreditCardRepository _repository;
            public ListCreditCardHandler(ILogger<ListCreditCardHandler> logger, ICreditCardRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<CreditCardDto>>> Handle(ListCreditCardQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.ListAsync(request.PageNumber, request.PageSize);
                return returnValue.ToResponse();
            }
        }
    }
}