-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT DPS.[DRIVER_PAYMENT_ID], S.[CREATE_DATE] AS SHIPMENT_CREATE_DATE,
	S.[DRIVER_ID], S.[SHIPMENT_STATUS] 
FROM [DRIVER_PAYMENTS_SHIPMENTS] DPS 
	INNER JOIN [SHIPMENTS] S 
			ON DPS.[SHIPMENT_ID] = S.[ID] 
WHERE S.[IsDeleted] = 0 
	AND DPS.[SHIPMENT_ID] = @PRM_DRIVER_PAYMENTS_SHIPMENTS_SHIPMENT_ID 
	AND S.[ID] = @PRM_SHIPMENTS_ID 
ORDER BY DPS.[DRIVER_PAYMENT_ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 