-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 DPS.[DRIVER_PAYMENT_ID], DPS.[SHIPMENT_ID] 
FROM [DRIVER_PAYMENTS_SHIPMENTS] DPS 
WHERE DPS.[SHIPMENT_ID] = @PRM_DRIVER_PAYMENT_SHIPMENT_SHIPMENT_ID 
ORDER BY DPS.[DRIVER_PAYMENT_ID], DPS.[SHIPMENT_ID] 