IF OBJECT_ID(N'dbo.DRIVER_PAYMENT_SHIPMENTS', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[DRIVER_PAYMENT_SHIPMENTS] (
        [DRIVER_PAYMENT_ID] int NOT NULL,
        [SHIPMENT_ID] int NOT NULL,
        CONSTRAINT [PK_DRIVER_PAYMENT_SHIPMENTS] PRIMARY KEY ([DRIVER_PAYMENT_ID], [SHIPMENT_ID])
    );
END;