IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENT_LOCATIONS', N'U') AND name = N'IX_SHIPMENT_LOCATIONS_LOCATION_ID_SHIPMENT_ID_IS_COMPLETED')
BEGIN
    CREATE INDEX [IX_SHIPMENT_LOCATIONS_LOCATION_ID_SHIPMENT_ID_IS_COMPLETED] ON [dbo].[SHIPMENT_LOCATIONS] ([LOCATION_ID], [SHIPMENT_ID], [IS_COMPLETED]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENT_LOCATIONS', N'U') AND name = N'IX_SHIPMENT_LOCATIONS_LOCATION_STATUS')
BEGIN
    CREATE INDEX [IX_SHIPMENT_LOCATIONS_LOCATION_STATUS] ON [dbo].[SHIPMENT_LOCATIONS] ([LOCATION_STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENT_LOCATIONS', N'U') AND name = N'IX_SHIPMENT_LOCATIONS_SHIPMENT_ID_IS_COMPLETED')
BEGIN
    CREATE INDEX [IX_SHIPMENT_LOCATIONS_SHIPMENT_ID_IS_COMPLETED] ON [dbo].[SHIPMENT_LOCATIONS] ([SHIPMENT_ID], [IS_COMPLETED]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENT_LOCATIONS', N'U') AND name = N'IX_SHIPMENT_LOCATIONS_SHIPMENT_ID_LOCATION_ID_SHIPMENT_ORDER')
BEGIN
    CREATE INDEX [IX_SHIPMENT_LOCATIONS_SHIPMENT_ID_LOCATION_ID_SHIPMENT_ORDER] ON [dbo].[SHIPMENT_LOCATIONS] ([SHIPMENT_ID], [LOCATION_ID], [SHIPMENT_ORDER]);
END