IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.STATES', N'U') AND name = N'IX_STATES_SHORT_NAME')
BEGIN
    CREATE INDEX [IX_STATES_SHORT_NAME] ON [dbo].[STATES] ([SHORT_NAME]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.STATES', N'U') AND name = N'IX_STATES_STATUS')
BEGIN
    CREATE INDEX [IX_STATES_STATUS] ON [dbo].[STATES] ([STATUS]);
END