IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVER_LOCATIONS', N'U') AND name = N'IX_DRIVER_LOCATIONS_DRIVER_ID_LOCATION_DATE')
BEGIN
    CREATE INDEX [IX_DRIVER_LOCATIONS_DRIVER_ID_LOCATION_DATE] ON [dbo].[DRIVER_LOCATIONS] ([DRIVER_ID], [LOCATION_DATE]);
END