IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CUSTOMER_LOGIN_ATTEMPTS', N'U') AND name = N'IX_CUSTOMER_LOGIN_ATTEMPTS_ATTEMPT_RESULT_LOGIN_DATE')
BEGIN
    CREATE INDEX [IX_CUSTOMER_LOGIN_ATTEMPTS_ATTEMPT_RESULT_LOGIN_DATE] ON [dbo].[CUSTOMER_LOGIN_ATTEMPTS] ([ATTEMPT_RESULT], [LOGIN_DATE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CUSTOMER_LOGIN_ATTEMPTS', N'U') AND name = N'IX_CUSTOMER_LOGIN_ATTEMPTS_CUSTOMER_ID_ATTEMPT_RESULT')
BEGIN
    CREATE INDEX [IX_CUSTOMER_LOGIN_ATTEMPTS_CUSTOMER_ID_ATTEMPT_RESULT] ON [dbo].[CUSTOMER_LOGIN_ATTEMPTS] ([CUSTOMER_ID], [ATTEMPT_RESULT]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CUSTOMER_LOGIN_ATTEMPTS', N'U') AND name = N'IX_CUSTOMER_LOGIN_ATTEMPTS_CUSTOMER_ID_LOGIN_DATE')
BEGIN
    CREATE INDEX [IX_CUSTOMER_LOGIN_ATTEMPTS_CUSTOMER_ID_LOGIN_DATE] ON [dbo].[CUSTOMER_LOGIN_ATTEMPTS] ([CUSTOMER_ID], [LOGIN_DATE]);
END