IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES', N'U') AND name = N'IX_SHIPMENT_PACKAGES_IsDeleted')
BEGIN
    CREATE INDEX [IX_SHIPMENT_PACKAGES_IsDeleted] ON [dbo].[SHIPMENT_PACKAGES] ([IsDeleted]);
END