IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMER_LOGIN_ATTEMPTS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMER_LOGIN_ATTEMPTS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMER_LOGIN_ATTEMPTS] ADD CONSTRAINT [FK_CUSTOMER_LOGIN_ATTEMPTS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END