IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_CUSTOMER_ID_CREATE_DATE')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_CUSTOMER_ID_CREATE_DATE] ON [dbo].[SHIPMENTS] ([CUSTOMER_ID], [CREATE_DATE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_CUSTOMER_ID_SHIPMENT_STATUS')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_CUSTOMER_ID_SHIPMENT_STATUS] ON [dbo].[SHIPMENTS] ([CUSTOMER_ID], [SHIPMENT_STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_DRIVER_ID_CUSTOMER_ID_PAYMENT_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_DRIVER_ID_CUSTOMER_ID_PAYMENT_ID] ON [dbo].[SHIPMENTS] ([DRIVER_ID], [CUSTOMER_ID], [PAYMENT_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_DRIVER_ID_STATE_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_DRIVER_ID_STATE_ID] ON [dbo].[SHIPMENTS] ([DRIVER_ID], [STATE_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_PAYMENT_ID_DRIVER_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_PAYMENT_ID_DRIVER_ID] ON [dbo].[SHIPMENTS] ([PAYMENT_ID], [DRIVER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_PAYMENT_ID_STATE_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_PAYMENT_ID_STATE_ID] ON [dbo].[SHIPMENTS] ([PAYMENT_ID], [STATE_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_SHIPMENT_STATUS')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_SHIPMENT_STATUS] ON [dbo].[SHIPMENTS] ([SHIPMENT_STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_SHIPMENT_TYPE')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_SHIPMENT_TYPE] ON [dbo].[SHIPMENTS] ([SHIPMENT_TYPE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_STATE_ID_CREATE_DATE')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_STATE_ID_CREATE_DATE] ON [dbo].[SHIPMENTS] ([STATE_ID], [CREATE_DATE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_VEHICLE_TYPE_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_VEHICLE_TYPE_ID] ON [dbo].[SHIPMENTS] ([VEHICLE_TYPE_ID]);
END