IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMERS_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMERS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMERS] ADD CONSTRAINT [FK_CUSTOMERS_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END