IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SM_OTP_VALIDATIONS', N'U') AND name = N'IX_SM_OTP_VALIDATIONS_GSM_NUMBER')
BEGIN
    CREATE INDEX [IX_SM_OTP_VALIDATIONS_GSM_NUMBER] ON [dbo].[SM_OTP_VALIDATIONS] ([GSM_NUMBER]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SM_OTP_VALIDATIONS', N'U') AND name = N'IX_SM_OTP_VALIDATIONS_RESULT_GSM_NUMBER')
BEGIN
    CREATE INDEX [IX_SM_OTP_VALIDATIONS_RESULT_GSM_NUMBER] ON [dbo].[SM_OTP_VALIDATIONS] ([RESULT], [GSM_NUMBER]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SM_OTP_VALIDATIONS', N'U') AND name = N'IX_SM_OTP_VALIDATIONS_SMS_OTP_ID')
BEGIN
    CREATE INDEX [IX_SM_OTP_VALIDATIONS_SMS_OTP_ID] ON [dbo].[SM_OTP_VALIDATIONS] ([SMS_OTP_ID]);
END