IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVER_PAYMENT_SHIPMENTS_DRIVER_PAYMENTS_DRIVER_PAYMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVER_PAYMENT_SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[DRIVER_PAYMENT_SHIPMENTS] ADD CONSTRAINT [FK_DRIVER_PAYMENT_SHIPMENTS_DRIVER_PAYMENTS_DRIVER_PAYMENT_ID] FOREIGN KEY ([DRIVER_PAYMENT_ID]) REFERENCES [dbo].[DRIVER_PAYMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVER_PAYMENT_SHIPMENTS_SHIPMENTS_SHIPMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVER_PAYMENT_SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[DRIVER_PAYMENT_SHIPMENTS] ADD CONSTRAINT [FK_DRIVER_PAYMENT_SHIPMENTS_SHIPMENTS_SHIPMENT_ID] FOREIGN KEY ([SHIPMENT_ID]) REFERENCES [dbo].[SHIPMENTS] ([ID]);
END