IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RECIPIENTS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.RECIPIENTS'))
BEGIN
    ALTER TABLE [dbo].[RECIPIENTS] ADD CONSTRAINT [FK_RECIPIENTS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END