IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SM_OTP_VALIDATIONS_SM_OTPS_SMS_OTP_ID' AND parent_object_id = OBJECT_ID(N'dbo.SM_OTP_VALIDATIONS'))
BEGIN
    ALTER TABLE [dbo].[SM_OTP_VALIDATIONS] ADD CONSTRAINT [FK_SM_OTP_VALIDATIONS_SM_OTPS_SMS_OTP_ID] FOREIGN KEY ([SMS_OTP_ID]) REFERENCES [dbo].[SM_OTPS] ([ID]);
END