IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRICE_MATRICES', N'U') AND name = N'IX_PRICE_MATRICES_STATE_ID_VEHICLE_TYPE_ID_RANGE_END')
BEGIN
    CREATE INDEX [IX_PRICE_MATRICES_STATE_ID_VEHICLE_TYPE_ID_RANGE_END] ON [dbo].[PRICE_MATRICES] ([STATE_ID], [VEHICLE_TYPE_ID], [RANGE_END]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRICE_MATRICES', N'U') AND name = N'IX_PRICE_MATRICES_VEHICLE_TYPE_ID')
BEGIN
    CREATE INDEX [IX_PRICE_MATRICES_VEHICLE_TYPE_ID] ON [dbo].[PRICE_MATRICES] ([VEHICLE_TYPE_ID]);
END