IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CUSTOMERS', N'U') AND name = N'IX_CUSTOMERS_DEVICE_TYPE')
BEGIN
    CREATE INDEX [IX_CUSTOMERS_DEVICE_TYPE] ON [dbo].[CUSTOMERS] ([DEVICE_TYPE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CUSTOMERS', N'U') AND name = N'IX_CUSTOMERS_GSM')
BEGIN
    CREATE INDEX [IX_CUSTOMERS_GSM] ON [dbo].[CUSTOMERS] ([GSM]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CUSTOMERS', N'U') AND name = N'IX_CUSTOMERS_PROFILE_ID')
BEGIN
    CREATE INDEX [IX_CUSTOMERS_PROFILE_ID] ON [dbo].[CUSTOMERS] ([PROFILE_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CUSTOMERS', N'U') AND name = N'IX_CUSTOMERS_STATE_ID')
BEGIN
    CREATE INDEX [IX_CUSTOMERS_STATE_ID] ON [dbo].[CUSTOMERS] ([STATE_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CUSTOMERS', N'U') AND name = N'IX_CUSTOMERS_STATUS')
BEGIN
    CREATE INDEX [IX_CUSTOMERS_STATUS] ON [dbo].[CUSTOMERS] ([STATUS]);
END