IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOCATIONS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOCATIONS'))
BEGIN
    ALTER TABLE [dbo].[LOCATIONS] ADD CONSTRAINT [FK_LOCATIONS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOCATIONS_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOCATIONS'))
BEGIN
    ALTER TABLE [dbo].[LOCATIONS] ADD CONSTRAINT [FK_LOCATIONS_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END