IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES', N'U') AND name = N'IX_SHIPMENT_PACKAGES_RECIPIENT_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENT_PACKAGES_RECIPIENT_ID] ON [dbo].[SHIPMENT_PACKAGES] ([RECIPIENT_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES', N'U') AND name = N'IX_SHIPMENT_PACKAGES_SENDER_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENT_PACKAGES_SENDER_ID] ON [dbo].[SHIPMENT_PACKAGES] ([SENDER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES', N'U') AND name = N'IX_SHIPMENT_PACKAGES_SHIPMENT_ID_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENT_PACKAGES_SHIPMENT_ID_ID] ON [dbo].[SHIPMENT_PACKAGES] ([SHIPMENT_ID], [ID]);
END