IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PAYMENTS', N'U') AND name = N'IX_PAYMENTS_CREDIT_CARD_ID')
BEGIN
    CREATE INDEX [IX_PAYMENTS_CREDIT_CARD_ID] ON [dbo].[PAYMENTS] ([CREDIT_CARD_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PAYMENTS', N'U') AND name = N'IX_PAYMENTS_PAYMENT_STATUS')
BEGIN
    CREATE INDEX [IX_PAYMENTS_PAYMENT_STATUS] ON [dbo].[PAYMENTS] ([PAYMENT_STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PAYMENTS', N'U') AND name = N'IX_PAYMENTS_PAYMENT_TYPE')
BEGIN
    CREATE INDEX [IX_PAYMENTS_PAYMENT_TYPE] ON [dbo].[PAYMENTS] ([PAYMENT_TYPE]);
END