IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_USER_STATES_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.USER_STATES'))
BEGIN
    ALTER TABLE [dbo].[USER_STATES] ADD CONSTRAINT [FK_USER_STATES_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END