IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RECIPIENTS', N'U') AND name = N'IX_RECIPIENTS_CUSTOMER_ID_ID')
BEGIN
    CREATE INDEX [IX_RECIPIENTS_CUSTOMER_ID_ID] ON [dbo].[RECIPIENTS] ([CUSTOMER_ID], [ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RECIPIENTS', N'U') AND name = N'IX_RECIPIENTS_CUSTOMER_ID_IS_STORED')
BEGIN
    CREATE INDEX [IX_RECIPIENTS_CUSTOMER_ID_IS_STORED] ON [dbo].[RECIPIENTS] ([CUSTOMER_ID], [IS_STORED]);
END