IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENT_LOCATIONS', N'U') AND name = N'IX_SHIPMENT_LOCATIONS_IsDeleted')
BEGIN
    CREATE INDEX [IX_SHIPMENT_LOCATIONS_IsDeleted] ON [dbo].[SHIPMENT_LOCATIONS] ([IsDeleted]);
END