IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVER_PAYMENTS_DRIVERS_DRIVER_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVER_PAYMENTS'))
BEGIN
    ALTER TABLE [dbo].[DRIVER_PAYMENTS] ADD CONSTRAINT [FK_DRIVER_PAYMENTS_DRIVERS_DRIVER_ID] FOREIGN KEY ([DRIVER_ID]) REFERENCES [dbo].[DRIVERS] ([ID]);
END