IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVERS', N'U') AND name = N'IX_DRIVERS_DEVICE_TYPE')
BEGIN
    CREATE INDEX [IX_DRIVERS_DEVICE_TYPE] ON [dbo].[DRIVERS] ([DEVICE_TYPE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVERS', N'U') AND name = N'IX_DRIVERS_DRIVER_STATUS')
BEGIN
    CREATE INDEX [IX_DRIVERS_DRIVER_STATUS] ON [dbo].[DRIVERS] ([DRIVER_STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVERS', N'U') AND name = N'IX_DRIVERS_GSM')
BEGIN
    CREATE INDEX [IX_DRIVERS_GSM] ON [dbo].[DRIVERS] ([GSM]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVERS', N'U') AND name = N'IX_DRIVERS_LAST_LOCATION_ID_DRIVER_STATUS_STATUS')
BEGIN
    CREATE INDEX [IX_DRIVERS_LAST_LOCATION_ID_DRIVER_STATUS_STATUS] ON [dbo].[DRIVERS] ([LAST_LOCATION_ID], [DRIVER_STATUS], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVERS', N'U') AND name = N'IX_DRIVERS_STATE_ID')
BEGIN
    CREATE INDEX [IX_DRIVERS_STATE_ID] ON [dbo].[DRIVERS] ([STATE_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVERS', N'U') AND name = N'IX_DRIVERS_STATUS')
BEGIN
    CREATE INDEX [IX_DRIVERS_STATUS] ON [dbo].[DRIVERS] ([STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVERS', N'U') AND name = N'IX_DRIVERS_VEHICLE_TYPE_ID_DRIVER_STATUS_STATUS')
BEGIN
    CREATE INDEX [IX_DRIVERS_VEHICLE_TYPE_ID_DRIVER_STATUS_STATUS] ON [dbo].[DRIVERS] ([VEHICLE_TYPE_ID], [DRIVER_STATUS], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVERS', N'U') AND name = N'IX_DRIVERS_VEHICLE_TYPE_ID_STATUS')
BEGIN
    CREATE INDEX [IX_DRIVERS_VEHICLE_TYPE_ID_STATUS] ON [dbo].[DRIVERS] ([VEHICLE_TYPE_ID], [STATUS]);
END