IF OBJECT_ID(N'dbo.USER_STATES', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[USER_STATES] (
        [STATE_ID] int NOT NULL,
        [USER_ID] int NOT NULL,
        CONSTRAINT [PK_USER_STATES] PRIMARY KEY ([STATE_ID], [USER_ID])
    );
END;