IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SENDERS', N'U') AND name = N'IX_SENDERS_CUSTOMER_ID_ID')
BEGIN
    CREATE INDEX [IX_SENDERS_CUSTOMER_ID_ID] ON [dbo].[SENDERS] ([CUSTOMER_ID], [ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SENDERS', N'U') AND name = N'IX_SENDERS_CUSTOMER_ID_IS_STORED')
BEGIN
    CREATE INDEX [IX_SENDERS_CUSTOMER_ID_IS_STORED] ON [dbo].[SENDERS] ([CUSTOMER_ID], [IS_STORED]);
END