IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_PACKAGES_SHIPMENTS_SHIPMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_PACKAGES] ADD CONSTRAINT [FK_SHIPMENT_PACKAGES_SHIPMENTS_SHIPMENT_ID] FOREIGN KEY ([SHIPMENT_ID]) REFERENCES [dbo].[SHIPMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_PACKAGES_RECIPIENTS_RECIPIENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_PACKAGES] ADD CONSTRAINT [FK_SHIPMENT_PACKAGES_RECIPIENTS_RECIPIENT_ID] FOREIGN KEY ([RECIPIENT_ID]) REFERENCES [dbo].[RECIPIENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_PACKAGES_SENDERS_SENDER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_PACKAGES] ADD CONSTRAINT [FK_SHIPMENT_PACKAGES_SENDERS_SENDER_ID] FOREIGN KEY ([SENDER_ID]) REFERENCES [dbo].[SENDERS] ([ID]);
END