IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_LOCATIONS_SHIPMENTS_SHIPMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_LOCATIONS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_LOCATIONS] ADD CONSTRAINT [FK_SHIPMENT_LOCATIONS_SHIPMENTS_SHIPMENT_ID] FOREIGN KEY ([SHIPMENT_ID]) REFERENCES [dbo].[SHIPMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_LOCATIONS_LOCATIONS_LOCATION_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_LOCATIONS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_LOCATIONS] ADD CONSTRAINT [FK_SHIPMENT_LOCATIONS_LOCATIONS_LOCATION_ID] FOREIGN KEY ([LOCATION_ID]) REFERENCES [dbo].[LOCATIONS] ([ID]);
END