IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SM_OTP_VALIDATIONS', N'U') AND name = N'IX_SM_OTP_VALIDATIONS_IsDeleted')
BEGIN
    CREATE INDEX [IX_SM_OTP_VALIDATIONS_IsDeleted] ON [dbo].[SM_OTP_VALIDATIONS] ([IsDeleted]);
END