IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CREDIT_CARDS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CREDIT_CARDS'))
BEGIN
    ALTER TABLE [dbo].[CREDIT_CARDS] ADD CONSTRAINT [FK_CREDIT_CARDS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMERS_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMERS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMERS] ADD CONSTRAINT [FK_CUSTOMERS_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMER_LOGIN_ATTEMPTS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMER_LOGIN_ATTEMPTS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMER_LOGIN_ATTEMPTS] ADD CONSTRAINT [FK_CUSTOMER_LOGIN_ATTEMPTS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVERS_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVERS'))
BEGIN
    ALTER TABLE [dbo].[DRIVERS] ADD CONSTRAINT [FK_DRIVERS_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVERS_VEHICLE_TYPES_VEHICLE_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVERS'))
BEGIN
    ALTER TABLE [dbo].[DRIVERS] ADD CONSTRAINT [FK_DRIVERS_VEHICLE_TYPES_VEHICLE_TYPE_ID] FOREIGN KEY ([VEHICLE_TYPE_ID]) REFERENCES [dbo].[VEHICLE_TYPES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVER_LOCATIONS_DRIVERS_DRIVER_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVER_LOCATIONS'))
BEGIN
    ALTER TABLE [dbo].[DRIVER_LOCATIONS] ADD CONSTRAINT [FK_DRIVER_LOCATIONS_DRIVERS_DRIVER_ID] FOREIGN KEY ([DRIVER_ID]) REFERENCES [dbo].[DRIVERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVER_PAYMENTS_DRIVERS_DRIVER_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVER_PAYMENTS'))
BEGIN
    ALTER TABLE [dbo].[DRIVER_PAYMENTS] ADD CONSTRAINT [FK_DRIVER_PAYMENTS_DRIVERS_DRIVER_ID] FOREIGN KEY ([DRIVER_ID]) REFERENCES [dbo].[DRIVERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVER_PAYMENT_SHIPMENTS_DRIVER_PAYMENTS_DRIVER_PAYMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVER_PAYMENT_SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[DRIVER_PAYMENT_SHIPMENTS] ADD CONSTRAINT [FK_DRIVER_PAYMENT_SHIPMENTS_DRIVER_PAYMENTS_DRIVER_PAYMENT_ID] FOREIGN KEY ([DRIVER_PAYMENT_ID]) REFERENCES [dbo].[DRIVER_PAYMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVER_PAYMENT_SHIPMENTS_SHIPMENTS_SHIPMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVER_PAYMENT_SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[DRIVER_PAYMENT_SHIPMENTS] ADD CONSTRAINT [FK_DRIVER_PAYMENT_SHIPMENTS_SHIPMENTS_SHIPMENT_ID] FOREIGN KEY ([SHIPMENT_ID]) REFERENCES [dbo].[SHIPMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOCATIONS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOCATIONS'))
BEGIN
    ALTER TABLE [dbo].[LOCATIONS] ADD CONSTRAINT [FK_LOCATIONS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOCATIONS_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOCATIONS'))
BEGIN
    ALTER TABLE [dbo].[LOCATIONS] ADD CONSTRAINT [FK_LOCATIONS_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PAYMENTS_CREDIT_CARDS_CREDIT_CARD_ID' AND parent_object_id = OBJECT_ID(N'dbo.PAYMENTS'))
BEGIN
    ALTER TABLE [dbo].[PAYMENTS] ADD CONSTRAINT [FK_PAYMENTS_CREDIT_CARDS_CREDIT_CARD_ID] FOREIGN KEY ([CREDIT_CARD_ID]) REFERENCES [dbo].[CREDIT_CARDS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRICE_MATRICES_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRICE_MATRICES'))
BEGIN
    ALTER TABLE [dbo].[PRICE_MATRICES] ADD CONSTRAINT [FK_PRICE_MATRICES_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRICE_MATRICES_VEHICLE_TYPES_VEHICLE_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRICE_MATRICES'))
BEGIN
    ALTER TABLE [dbo].[PRICE_MATRICES] ADD CONSTRAINT [FK_PRICE_MATRICES_VEHICLE_TYPES_VEHICLE_TYPE_ID] FOREIGN KEY ([VEHICLE_TYPE_ID]) REFERENCES [dbo].[VEHICLE_TYPES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RECIPIENTS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.RECIPIENTS'))
BEGIN
    ALTER TABLE [dbo].[RECIPIENTS] ADD CONSTRAINT [FK_RECIPIENTS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SENDERS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SENDERS'))
BEGIN
    ALTER TABLE [dbo].[SENDERS] ADD CONSTRAINT [FK_SENDERS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_DRIVERS_DRIVER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_DRIVERS_DRIVER_ID] FOREIGN KEY ([DRIVER_ID]) REFERENCES [dbo].[DRIVERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_PAYMENTS_PAYMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_PAYMENTS_PAYMENT_ID] FOREIGN KEY ([PAYMENT_ID]) REFERENCES [dbo].[PAYMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_VEHICLE_TYPES_VEHICLE_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_VEHICLE_TYPES_VEHICLE_TYPE_ID] FOREIGN KEY ([VEHICLE_TYPE_ID]) REFERENCES [dbo].[VEHICLE_TYPES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_LOCATIONS_SHIPMENTS_SHIPMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_LOCATIONS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_LOCATIONS] ADD CONSTRAINT [FK_SHIPMENT_LOCATIONS_SHIPMENTS_SHIPMENT_ID] FOREIGN KEY ([SHIPMENT_ID]) REFERENCES [dbo].[SHIPMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_LOCATIONS_LOCATIONS_LOCATION_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_LOCATIONS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_LOCATIONS] ADD CONSTRAINT [FK_SHIPMENT_LOCATIONS_LOCATIONS_LOCATION_ID] FOREIGN KEY ([LOCATION_ID]) REFERENCES [dbo].[LOCATIONS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_PACKAGES_SHIPMENTS_SHIPMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_PACKAGES] ADD CONSTRAINT [FK_SHIPMENT_PACKAGES_SHIPMENTS_SHIPMENT_ID] FOREIGN KEY ([SHIPMENT_ID]) REFERENCES [dbo].[SHIPMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_PACKAGES_RECIPIENTS_RECIPIENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_PACKAGES] ADD CONSTRAINT [FK_SHIPMENT_PACKAGES_RECIPIENTS_RECIPIENT_ID] FOREIGN KEY ([RECIPIENT_ID]) REFERENCES [dbo].[RECIPIENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENT_PACKAGES_SENDERS_SENDER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENT_PACKAGES'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENT_PACKAGES] ADD CONSTRAINT [FK_SHIPMENT_PACKAGES_SENDERS_SENDER_ID] FOREIGN KEY ([SENDER_ID]) REFERENCES [dbo].[SENDERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SM_OTP_VALIDATIONS_SM_OTPS_SMS_OTP_ID' AND parent_object_id = OBJECT_ID(N'dbo.SM_OTP_VALIDATIONS'))
BEGIN
    ALTER TABLE [dbo].[SM_OTP_VALIDATIONS] ADD CONSTRAINT [FK_SM_OTP_VALIDATIONS_SM_OTPS_SMS_OTP_ID] FOREIGN KEY ([SMS_OTP_ID]) REFERENCES [dbo].[SM_OTPS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_USER_STATES_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.USER_STATES'))
BEGIN
    ALTER TABLE [dbo].[USER_STATES] ADD CONSTRAINT [FK_USER_STATES_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END