IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PAYMENTS_CREDIT_CARDS_CREDIT_CARD_ID' AND parent_object_id = OBJECT_ID(N'dbo.PAYMENTS'))
BEGIN
    ALTER TABLE [dbo].[PAYMENTS] ADD CONSTRAINT [FK_PAYMENTS_CREDIT_CARDS_CREDIT_CARD_ID] FOREIGN KEY ([CREDIT_CARD_ID]) REFERENCES [dbo].[CREDIT_CARDS] ([ID]);
END