IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_DRIVERS_DRIVER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_DRIVERS_DRIVER_ID] FOREIGN KEY ([DRIVER_ID]) REFERENCES [dbo].[DRIVERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_PAYMENTS_PAYMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_PAYMENTS_PAYMENT_ID] FOREIGN KEY ([PAYMENT_ID]) REFERENCES [dbo].[PAYMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_VEHICLE_TYPES_VEHICLE_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_VEHICLE_TYPES_VEHICLE_TYPE_ID] FOREIGN KEY ([VEHICLE_TYPE_ID]) REFERENCES [dbo].[VEHICLE_TYPES] ([ID]);
END