IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVER_LOCATIONS', N'U') AND name = N'IX_DRIVER_LOCATIONS_IsDeleted')
BEGIN
    CREATE INDEX [IX_DRIVER_LOCATIONS_IsDeleted] ON [dbo].[DRIVER_LOCATIONS] ([IsDeleted]);
END