IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CREDIT_CARDS', N'U') AND name = N'IX_CREDIT_CARDS_CUSTOMER_ID_ID')
BEGIN
    CREATE INDEX [IX_CREDIT_CARDS_CUSTOMER_ID_ID] ON [dbo].[CREDIT_CARDS] ([CUSTOMER_ID], [ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CREDIT_CARDS', N'U') AND name = N'IX_CREDIT_CARDS_CUSTOMER_ID_IS_STORED')
BEGIN
    CREATE INDEX [IX_CREDIT_CARDS_CUSTOMER_ID_IS_STORED] ON [dbo].[CREDIT_CARDS] ([CUSTOMER_ID], [IS_STORED]);
END