IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CUSTOMER_LOGIN_ATTEMPTS', N'U') AND name = N'IX_CUSTOMER_LOGIN_ATTEMPTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_CUSTOMER_LOGIN_ATTEMPTS_IsDeleted] ON [dbo].[CUSTOMER_LOGIN_ATTEMPTS] ([IsDeleted]);
END