IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVER_PAYMENTS', N'U') AND name = N'IX_DRIVER_PAYMENTS_DRIVER_ID')
BEGIN
    CREATE INDEX [IX_DRIVER_PAYMENTS_DRIVER_ID] ON [dbo].[DRIVER_PAYMENTS] ([DRIVER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVER_PAYMENTS', N'U') AND name = N'IX_DRIVER_PAYMENTS_USER_ID')
BEGIN
    CREATE INDEX [IX_DRIVER_PAYMENTS_USER_ID] ON [dbo].[DRIVER_PAYMENTS] ([USER_ID]);
END