IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVER_PAYMENTS', N'U') AND name = N'IX_DRIVER_PAYMENTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_DRIVER_PAYMENTS_IsDeleted] ON [dbo].[DRIVER_PAYMENTS] ([IsDeleted]);
END