IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.VEHICLE_TYPES', N'U') AND name = N'IX_VEHICLE_TYPES_IS_DELETED')
BEGIN
    CREATE INDEX [IX_VEHICLE_TYPES_IS_DELETED] ON [dbo].[VEHICLE_TYPES] ([IS_DELETED]);
END