IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRICE_MATRICES_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRICE_MATRICES'))
BEGIN
    ALTER TABLE [dbo].[PRICE_MATRICES] ADD CONSTRAINT [FK_PRICE_MATRICES_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRICE_MATRICES_VEHICLE_TYPES_VEHICLE_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRICE_MATRICES'))
BEGIN
    ALTER TABLE [dbo].[PRICE_MATRICES] ADD CONSTRAINT [FK_PRICE_MATRICES_VEHICLE_TYPES_VEHICLE_TYPE_ID] FOREIGN KEY ([VEHICLE_TYPE_ID]) REFERENCES [dbo].[VEHICLE_TYPES] ([ID]);
END