IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DRIVER_COMMISSIONS', N'U') AND name = N'IX_DRIVER_COMMISSIONS_IsDeleted')
BEGIN
    CREATE INDEX [IX_DRIVER_COMMISSIONS_IsDeleted] ON [dbo].[DRIVER_COMMISSIONS] ([IsDeleted]);
END