IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CREDIT_CARDS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CREDIT_CARDS'))
BEGIN
    ALTER TABLE [dbo].[CREDIT_CARDS] ADD CONSTRAINT [FK_CREDIT_CARDS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END