IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVERS_STATES_STATE_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVERS'))
BEGIN
    ALTER TABLE [dbo].[DRIVERS] ADD CONSTRAINT [FK_DRIVERS_STATES_STATE_ID] FOREIGN KEY ([STATE_ID]) REFERENCES [dbo].[STATES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DRIVERS_VEHICLE_TYPES_VEHICLE_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.DRIVERS'))
BEGIN
    ALTER TABLE [dbo].[DRIVERS] ADD CONSTRAINT [FK_DRIVERS_VEHICLE_TYPES_VEHICLE_TYPE_ID] FOREIGN KEY ([VEHICLE_TYPE_ID]) REFERENCES [dbo].[VEHICLE_TYPES] ([ID]);
END