IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.LOCATIONS', N'U') AND name = N'IX_LOCATIONS_CUSTOMER_ID_ALIAS_NAME')
BEGIN
    CREATE INDEX [IX_LOCATIONS_CUSTOMER_ID_ALIAS_NAME] ON [dbo].[LOCATIONS] ([CUSTOMER_ID], [ALIAS_NAME]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.LOCATIONS', N'U') AND name = N'IX_LOCATIONS_CUSTOMER_ID_ID')
BEGIN
    CREATE INDEX [IX_LOCATIONS_CUSTOMER_ID_ID] ON [dbo].[LOCATIONS] ([CUSTOMER_ID], [ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.LOCATIONS', N'U') AND name = N'IX_LOCATIONS_STATE_ID')
BEGIN
    CREATE INDEX [IX_LOCATIONS_STATE_ID] ON [dbo].[LOCATIONS] ([STATE_ID]);
END