// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.IdentityModule.Domain.Entities;
using QuickCode.Freytz.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.IdentityModule.Application.Dtos.PortalMenu;
using QuickCode.Freytz.IdentityModule.Domain.Enums;

namespace QuickCode.Freytz.IdentityModule.Application.Features.PortalMenu
{
    public class DeletePortalMenuCommand : IRequest<Response<bool>>
    {
        public PortalMenuDto request { get; set; }

        public DeletePortalMenuCommand(PortalMenuDto request)
        {
            this.request = request;
        }

        public class DeletePortalMenuHandler : IRequestHandler<DeletePortalMenuCommand, Response<bool>>
        {
            private readonly ILogger<DeletePortalMenuHandler> _logger;
            private readonly IPortalMenuRepository _repository;
            public DeletePortalMenuHandler(ILogger<DeletePortalMenuHandler> logger, IPortalMenuRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(DeletePortalMenuCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.DeleteAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}