-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS TOTAL_COUNT,
	SUM(DP.[PAYMENT_AMOUNT]) AS TOTAL_AMOUNT 
FROM [DRIVER_PAYMENTS] DP 
WHERE DP.[IsDeleted] = 0 
	AND DP.[PAYMENT_DATE] > DATEADD(DAY, -30,
	GETDATE()) 