// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Freytz.MainModule.Application.Dtos.CustomerLoginAttempt;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories;
internal static class CustomerLoginAttemptCrudSqlBindings
{
    public const string StoreTableName = "CUSTOMER_LOGIN_ATTEMPTS";
    public const string ParameterNamePrefix = "CUSTOMER_LOGIN_ATTEMPT";
    public const string IdParameterName = "PRM_CUSTOMER_LOGIN_ATTEMPT_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByCustomer = "GetByCustomer";
        public const string GetByPk = "GetByPk";
        public const string GetFailedByCustomer = "GetFailedByCustomer";
        public const string GetFailedCount = "GetFailedCount";
        public const string GetRecent = "GetRecent";
        public const string GetWithCustomer = "GetWithCustomer";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CUSTOMER_ID", nameof(CustomerLoginAttemptDto.CustomerId)),
        ("CLIENT_IP", nameof(CustomerLoginAttemptDto.ClientIp)),
        ("LOGIN_DATE", nameof(CustomerLoginAttemptDto.LoginDate)),
        ("ATTEMPT_RESULT", nameof(CustomerLoginAttemptDto.AttemptResult))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CUSTOMER_ID", nameof(CustomerLoginAttemptDto.CustomerId)),
        ("CLIENT_IP", nameof(CustomerLoginAttemptDto.ClientIp)),
        ("LOGIN_DATE", nameof(CustomerLoginAttemptDto.LoginDate)),
        ("ATTEMPT_RESULT", nameof(CustomerLoginAttemptDto.AttemptResult)),
        ("ID", nameof(CustomerLoginAttemptDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CustomerLoginAttemptDto.Id))
    };
}