// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverPayment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverPayment
{
    public class GetByDateRangeQuery : IRequest<Response<List<GetByDateRangeResponseDto>>>
    {
        public DateTime DriverPaymentPaymentDateFrom { get; set; }
        public DateTime DriverPaymentPaymentDateTo { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetByDateRangeQuery(DateTime driverPaymentPaymentDateFrom, DateTime driverPaymentPaymentDateTo, int? pageNumber, int? pageSize)
        {
            this.DriverPaymentPaymentDateFrom = driverPaymentPaymentDateFrom;
            this.DriverPaymentPaymentDateTo = driverPaymentPaymentDateTo;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetByDateRangeHandler : IRequestHandler<GetByDateRangeQuery, Response<List<GetByDateRangeResponseDto>>>
        {
            private readonly ILogger<GetByDateRangeHandler> _logger;
            private readonly IDriverPaymentRepository _repository;
            public GetByDateRangeHandler(ILogger<GetByDateRangeHandler> logger, IDriverPaymentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetByDateRangeResponseDto>>> Handle(GetByDateRangeQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByDateRangeAsync(request.DriverPaymentPaymentDateFrom, request.DriverPaymentPaymentDateTo, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}