// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverPayment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverPayment
{
    public class GetDriverTotalQuery : IRequest<Response<GetDriverTotalResponseDto>>
    {
        public int DriverPaymentDriverId { get; set; }

        public GetDriverTotalQuery(int driverPaymentDriverId)
        {
            this.DriverPaymentDriverId = driverPaymentDriverId;
        }

        public class GetDriverTotalHandler : IRequestHandler<GetDriverTotalQuery, Response<GetDriverTotalResponseDto>>
        {
            private readonly ILogger<GetDriverTotalHandler> _logger;
            private readonly IDriverPaymentRepository _repository;
            public GetDriverTotalHandler(ILogger<GetDriverTotalHandler> logger, IDriverPaymentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<GetDriverTotalResponseDto>> Handle(GetDriverTotalQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetDriverTotalAsync(request.DriverPaymentDriverId);
                return returnValue.ToResponse();
            }
        }
    }
}