// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverPayment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverPayment
{
    public class GetWithDriverQuery : IRequest<Response<List<GetWithDriverResponseDto>>>
    {
        public int DriverPaymentsDriverId { get; set; }
        public int DriversId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetWithDriverQuery(int driverPaymentsDriverId, int driversId, int? pageNumber, int? pageSize)
        {
            this.DriverPaymentsDriverId = driverPaymentsDriverId;
            this.DriversId = driversId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetWithDriverHandler : IRequestHandler<GetWithDriverQuery, Response<List<GetWithDriverResponseDto>>>
        {
            private readonly ILogger<GetWithDriverHandler> _logger;
            private readonly IDriverPaymentRepository _repository;
            public GetWithDriverHandler(ILogger<GetWithDriverHandler> logger, IDriverPaymentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetWithDriverResponseDto>>> Handle(GetWithDriverQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetWithDriverAsync(request.DriverPaymentsDriverId, request.DriversId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}