// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentPackage;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.ShipmentPackage
{
    public class GetByShipmentQuery : IRequest<Response<List<GetByShipmentResponseDto>>>
    {
        public int ShipmentPackageShipmentId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetByShipmentQuery(int shipmentPackageShipmentId, int? pageNumber, int? pageSize)
        {
            this.ShipmentPackageShipmentId = shipmentPackageShipmentId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetByShipmentHandler : IRequestHandler<GetByShipmentQuery, Response<List<GetByShipmentResponseDto>>>
        {
            private readonly ILogger<GetByShipmentHandler> _logger;
            private readonly IShipmentPackageRepository _repository;
            public GetByShipmentHandler(ILogger<GetByShipmentHandler> logger, IShipmentPackageRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetByShipmentResponseDto>>> Handle(GetByShipmentQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByShipmentAsync(request.ShipmentPackageShipmentId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}