// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentPackage;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.ShipmentPackage
{
    public class GetByRecipientQuery : IRequest<Response<List<GetByRecipientResponseDto>>>
    {
        public int ShipmentPackageRecipientId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetByRecipientQuery(int shipmentPackageRecipientId, int? pageNumber, int? pageSize)
        {
            this.ShipmentPackageRecipientId = shipmentPackageRecipientId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetByRecipientHandler : IRequestHandler<GetByRecipientQuery, Response<List<GetByRecipientResponseDto>>>
        {
            private readonly ILogger<GetByRecipientHandler> _logger;
            private readonly IShipmentPackageRepository _repository;
            public GetByRecipientHandler(ILogger<GetByRecipientHandler> logger, IShipmentPackageRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetByRecipientResponseDto>>> Handle(GetByRecipientQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByRecipientAsync(request.ShipmentPackageRecipientId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}