// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Freytz.MainModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Location
    {
        public static class Query
        {
            private const string _prefix = "MainModule.Location.Query";
            private const string _sqlScriptStem = "Location";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetCustomerLocation => ResourceKey($"{_sqlScriptStem}.GetCustomerLocation.g.sql");
            public static string GetByCustomer => ResourceKey($"{_sqlScriptStem}.GetByCustomer.g.sql");
            public static string GetFavoritesByCustomer => ResourceKey($"{_sqlScriptStem}.GetFavoritesByCustomer.g.sql");
            public static string GetByState => ResourceKey($"{_sqlScriptStem}.GetByState.g.sql");
            public static string SearchByAlias => ResourceKey($"{_sqlScriptStem}.SearchByAlias.g.sql");
            public static string GetWithCustomer => ResourceKey($"{_sqlScriptStem}.GetWithCustomer.g.sql");
            public static string GetWithState => ResourceKey($"{_sqlScriptStem}.GetWithState.g.sql");
        }
    }
}