// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.PriceMatrix;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.PriceMatrix
{
    public class GetWithStateQuery : IRequest<Response<List<GetWithStateResponseDto>>>
    {
        public int PriceMatricesStateId { get; set; }
        public int StatesId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetWithStateQuery(int priceMatricesStateId, int statesId, int? pageNumber, int? pageSize)
        {
            this.PriceMatricesStateId = priceMatricesStateId;
            this.StatesId = statesId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetWithStateHandler : IRequestHandler<GetWithStateQuery, Response<List<GetWithStateResponseDto>>>
        {
            private readonly ILogger<GetWithStateHandler> _logger;
            private readonly IPriceMatrixRepository _repository;
            public GetWithStateHandler(ILogger<GetWithStateHandler> logger, IPriceMatrixRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetWithStateResponseDto>>> Handle(GetWithStateQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetWithStateAsync(request.PriceMatricesStateId, request.StatesId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}