// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Freytz.Application.Contracts.Mediator;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Web.Controllers;
using QuickCode.Freytz.MainModule.Application.Dtos.Driver;
using QuickCode.Freytz.MainModule.Application.Features.Driver;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Api.Controllers
{
    public partial class DriversController : QuickCodeBaseApiController
    {
        private readonly IMediator mediator;
        private readonly ILogger<DriversController> logger;
        private readonly IServiceProvider serviceProvider;
        public DriversController(IMediator mediator, IServiceProvider serviceProvider, ILogger<DriversController> logger)
        {
            this.mediator = mediator;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<DriverDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await mediator.Send(new ListDriverQuery(page, size));
            if (HandleResponseError(response, logger, "Driver", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await mediator.Send(new TotalCountDriverQuery());
            if (HandleResponseError(response, logger, "Driver") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(DriverDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await mediator.Send(new GetItemDriverQuery(id));
            if (HandleResponseError(response, logger, "Driver", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(DriverDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(DriverDto model)
        {
            var response = await mediator.Send(new InsertDriverCommand(model));
            if (HandleResponseError(response, logger, "Driver") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, DriverDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await mediator.Send(new UpdateDriverCommand(id, model));
            if (HandleResponseError(response, logger, "Driver", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await mediator.Send(new DeleteItemDriverCommand(id));
            if (HandleResponseError(response, logger, "Driver", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("driver-login/{driverEmail}/{driverPassword}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(DriverLoginResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DriverLoginAsync(string driverEmail, string driverPassword)
        {
            var response = await mediator.Send(new DriverLoginQuery(driverEmail, driverPassword));
            if (HandleResponseError(response, logger, "Driver", $"DriverEmail: '{driverEmail}', DriverPassword: '{driverPassword}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-email/{driverEmail}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetByEmailResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByEmailAsync(string driverEmail)
        {
            var response = await mediator.Send(new GetByEmailQuery(driverEmail));
            if (HandleResponseError(response, logger, "Driver", $"DriverEmail: '{driverEmail}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-gsm/{driverGsm}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetByGsmResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByGsmAsync(string driverGsm)
        {
            var response = await mediator.Send(new GetByGsmQuery(driverGsm));
            if (HandleResponseError(response, logger, "Driver", $"DriverGsm: '{driverGsm}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-password-by-gsm/{driverGsm}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetPasswordByGsmResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetPasswordByGsmAsync(string driverGsm)
        {
            var response = await mediator.Send(new GetPasswordByGsmQuery(driverGsm));
            if (HandleResponseError(response, logger, "Driver", $"DriverGsm: '{driverGsm}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-password-by-email/{driverEmail}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetPasswordByEmailResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetPasswordByEmailAsync(string driverEmail)
        {
            var response = await mediator.Send(new GetPasswordByEmailQuery(driverEmail));
            if (HandleResponseError(response, logger, "Driver", $"DriverEmail: '{driverEmail}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-photo/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetPhotoResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetPhotoAsync(int driverId)
        {
            var response = await mediator.Send(new GetPhotoQuery(driverId));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-max-distance/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetMaxDistanceResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetMaxDistanceAsync(int driverId)
        {
            var response = await mediator.Send(new GetMaxDistanceQuery(driverId));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-driver-status/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetDriverStatusResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetDriverStatusAsync(int driverId)
        {
            var response = await mediator.Send(new GetDriverStatusQuery(driverId));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("check-driver-device/{driverDeviceType}/{driverDeviceId}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CheckDriverDeviceAsync(DeviceType driverDeviceType, string driverDeviceId)
        {
            var response = await mediator.Send(new CheckDriverDeviceQuery(driverDeviceType, driverDeviceId));
            if (HandleResponseError(response, logger, "Driver", $"DriverDeviceType: '{driverDeviceType}', DriverDeviceId: '{driverDeviceId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-status/{driverStatus}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByStatusResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByStatusAsync(SystemStatus driverStatus, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByStatusQuery(driverStatus, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"DriverStatus: '{driverStatus}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-active")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetActiveResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetActiveAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetActiveQuery(pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-driver-status/{driverDriverStatus}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByDriverStatusResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByDriverStatusAsync(DriverStatus driverDriverStatus, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByDriverStatusQuery(driverDriverStatus, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"DriverDriverStatus: '{driverDriverStatus}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-available")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetAvailableResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetAvailableAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetAvailableQuery(pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("find-available-by-vehicle/{driverVehicleTypeId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<FindAvailableByVehicleResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> FindAvailableByVehicleAsync(int driverVehicleTypeId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new FindAvailableByVehicleQuery(driverVehicleTypeId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"DriverVehicleTypeId: '{driverVehicleTypeId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-state/{driverStateId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByStateResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByStateAsync(int driverStateId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByStateQuery(driverStateId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"DriverStateId: '{driverStateId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-vehicle-type/{driverVehicleTypeId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByVehicleTypeResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByVehicleTypeAsync(int driverVehicleTypeId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByVehicleTypeQuery(driverVehicleTypeId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"DriverVehicleTypeId: '{driverVehicleTypeId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("search-by-name/{driverName}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<SearchByNameResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> SearchByNameAsync(string driverName, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new SearchByNameQuery(driverName, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"DriverName: '{driverName}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-with-vehicle-type/{driversVehicleTypeId:int}/{vehicleTypesId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetWithVehicleTypeResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetWithVehicleTypeAsync(int driversVehicleTypeId, int vehicleTypesId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetWithVehicleTypeQuery(driversVehicleTypeId, vehicleTypesId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"DriversVehicleTypeId: '{driversVehicleTypeId}', VehicleTypesId: '{vehicleTypesId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-with-state/{driversStateId:int}/{statesId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetWithStateResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetWithStateAsync(int driversStateId, int statesId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetWithStateQuery(driversStateId, statesId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"DriversStateId: '{driversStateId}', StatesId: '{statesId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-available-with-location/{driversLastLocationId:int}/{driverLocationsId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetAvailableWithLocationResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetAvailableWithLocationAsync(int driversLastLocationId, int driverLocationsId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetAvailableWithLocationQuery(driversLastLocationId, driverLocationsId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "Driver", $"DriversLastLocationId: '{driversLastLocationId}', DriverLocationsId: '{driverLocationsId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-active-count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(long))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetActiveCountAsync()
        {
            var response = await mediator.Send(new GetActiveCountQuery());
            if (HandleResponseError(response, logger, "Driver", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-available-count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(long))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetAvailableCountAsync()
        {
            var response = await mediator.Send(new GetAvailableCountQuery());
            if (HandleResponseError(response, logger, "Driver", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("exists-by-email/{driverEmail}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ExistsByEmailAsync(string driverEmail)
        {
            var response = await mediator.Send(new ExistsByEmailQuery(driverEmail));
            if (HandleResponseError(response, logger, "Driver", $"DriverEmail: '{driverEmail}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("exists-by-gsm/{driverGsm}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ExistsByGsmAsync(string driverGsm)
        {
            var response = await mediator.Send(new ExistsByGsmQuery(driverGsm));
            if (HandleResponseError(response, logger, "Driver", $"DriverGsm: '{driverGsm}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-driver-status/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateDriverStatusAsync(int driverId, [FromBody] UpdateDriverStatusRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdateDriverStatusCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("set-available/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> SetAvailableAsync(int driverId, [FromBody] SetAvailableRequestDto updateRequest)
        {
            var response = await mediator.Send(new SetAvailableCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("set-busy/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> SetBusyAsync(int driverId, [FromBody] SetBusyRequestDto updateRequest)
        {
            var response = await mediator.Send(new SetBusyCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-status/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateStatusAsync(int driverId, [FromBody] UpdateStatusRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdateStatusCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-device/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateDeviceAsync(int driverId, [FromBody] UpdateDeviceRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdateDeviceCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-firebase-id/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateFirebaseIdAsync(int driverId, [FromBody] UpdateFirebaseIdRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdateFirebaseIdCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-password/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdatePasswordAsync(int driverId, [FromBody] UpdatePasswordRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdatePasswordCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-profile/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateProfileAsync(int driverId, [FromBody] UpdateProfileRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdateProfileCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-photo/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdatePhotoAsync(int driverId, [FromBody] UpdatePhotoRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdatePhotoCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-max-distance/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateMaxDistanceAsync(int driverId, [FromBody] UpdateMaxDistanceRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdateMaxDistanceCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-last-location/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateLastLocationAsync(int driverId, [FromBody] UpdateLastLocationRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdateLastLocationCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-payment-account/{driverId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdatePaymentAccountAsync(int driverId, [FromBody] UpdatePaymentAccountRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdatePaymentAccountCommand(driverId, updateRequest));
            if (HandleResponseError(response, logger, "Driver", $"DriverId: '{driverId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}