// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Freytz.Application.Contracts.Mediator;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Web.Controllers;
using QuickCode.Freytz.MainModule.Application.Dtos.PriceMatrix;
using QuickCode.Freytz.MainModule.Application.Features.PriceMatrix;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Api.Controllers
{
    public partial class PriceMatricesController : QuickCodeBaseApiController
    {
        private readonly IMediator mediator;
        private readonly ILogger<PriceMatricesController> logger;
        private readonly IServiceProvider serviceProvider;
        public PriceMatricesController(IMediator mediator, IServiceProvider serviceProvider, ILogger<PriceMatricesController> logger)
        {
            this.mediator = mediator;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<PriceMatrixDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await mediator.Send(new ListPriceMatrixQuery(page, size));
            if (HandleResponseError(response, logger, "PriceMatrix", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await mediator.Send(new TotalCountPriceMatrixQuery());
            if (HandleResponseError(response, logger, "PriceMatrix") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(PriceMatrixDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await mediator.Send(new GetItemPriceMatrixQuery(id));
            if (HandleResponseError(response, logger, "PriceMatrix", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(PriceMatrixDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(PriceMatrixDto model)
        {
            var response = await mediator.Send(new InsertPriceMatrixCommand(model));
            if (HandleResponseError(response, logger, "PriceMatrix") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, PriceMatrixDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await mediator.Send(new UpdatePriceMatrixCommand(id, model));
            if (HandleResponseError(response, logger, "PriceMatrix", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await mediator.Send(new DeleteItemPriceMatrixCommand(id));
            if (HandleResponseError(response, logger, "PriceMatrix", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("calculate-price/{priceMatrixRangeEnd:decimal}/{priceMatrixStateId:int}/{priceMatrixVehicleTypeId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(CalculatePriceResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CalculatePriceAsync(decimal priceMatrixRangeEnd, int priceMatrixStateId, int priceMatrixVehicleTypeId)
        {
            var response = await mediator.Send(new CalculatePriceQuery(priceMatrixRangeEnd, priceMatrixStateId, priceMatrixVehicleTypeId));
            if (HandleResponseError(response, logger, "PriceMatrix", $"PriceMatrixRangeEnd: '{priceMatrixRangeEnd}', PriceMatrixStateId: '{priceMatrixStateId}', PriceMatrixVehicleTypeId: '{priceMatrixVehicleTypeId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-state/{priceMatrixStateId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByStateResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByStateAsync(int priceMatrixStateId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByStateQuery(priceMatrixStateId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "PriceMatrix", $"PriceMatrixStateId: '{priceMatrixStateId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-vehicle-type/{priceMatrixVehicleTypeId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByVehicleTypeResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByVehicleTypeAsync(int priceMatrixVehicleTypeId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByVehicleTypeQuery(priceMatrixVehicleTypeId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "PriceMatrix", $"PriceMatrixVehicleTypeId: '{priceMatrixVehicleTypeId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-state-and-vehicle/{priceMatrixStateId:int}/{priceMatrixVehicleTypeId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByStateAndVehicleResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByStateAndVehicleAsync(int priceMatrixStateId, int priceMatrixVehicleTypeId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByStateAndVehicleQuery(priceMatrixStateId, priceMatrixVehicleTypeId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "PriceMatrix", $"PriceMatrixStateId: '{priceMatrixStateId}', PriceMatrixVehicleTypeId: '{priceMatrixVehicleTypeId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-with-state/{priceMatricesStateId:int}/{statesId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetWithStateResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetWithStateAsync(int priceMatricesStateId, int statesId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetWithStateQuery(priceMatricesStateId, statesId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "PriceMatrix", $"PriceMatricesStateId: '{priceMatricesStateId}', StatesId: '{statesId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-with-vehicle-type/{priceMatricesVehicleTypeId:int}/{vehicleTypesId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetWithVehicleTypeResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetWithVehicleTypeAsync(int priceMatricesVehicleTypeId, int vehicleTypesId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetWithVehicleTypeQuery(priceMatricesVehicleTypeId, vehicleTypesId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "PriceMatrix", $"PriceMatricesVehicleTypeId: '{priceMatricesVehicleTypeId}', VehicleTypesId: '{vehicleTypesId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}