// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Freytz.Application.Contracts.Mediator;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Web.Controllers;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentLocation;
using QuickCode.Freytz.MainModule.Application.Features.ShipmentLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Api.Controllers
{
    public partial class ShipmentLocationsController : QuickCodeBaseApiController
    {
        private readonly IMediator mediator;
        private readonly ILogger<ShipmentLocationsController> logger;
        private readonly IServiceProvider serviceProvider;
        public ShipmentLocationsController(IMediator mediator, IServiceProvider serviceProvider, ILogger<ShipmentLocationsController> logger)
        {
            this.mediator = mediator;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<ShipmentLocationDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await mediator.Send(new ListShipmentLocationQuery(page, size));
            if (HandleResponseError(response, logger, "ShipmentLocation", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await mediator.Send(new TotalCountShipmentLocationQuery());
            if (HandleResponseError(response, logger, "ShipmentLocation") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ShipmentLocationDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await mediator.Send(new GetItemShipmentLocationQuery(id));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(ShipmentLocationDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(ShipmentLocationDto model)
        {
            var response = await mediator.Send(new InsertShipmentLocationCommand(model));
            if (HandleResponseError(response, logger, "ShipmentLocation") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, ShipmentLocationDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await mediator.Send(new UpdateShipmentLocationCommand(id, model));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await mediator.Send(new DeleteItemShipmentLocationCommand(id));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-shipment-locations/{shipmentLocationShipmentId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetShipmentLocationsResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetShipmentLocationsAsync(int shipmentLocationShipmentId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetShipmentLocationsQuery(shipmentLocationShipmentId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-shipment-location-status/{shipmentLocationShipmentId:int}/{shipmentLocationLocationId:int}/{shipmentLocationShipmentOrder:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetShipmentLocationStatusResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetShipmentLocationStatusAsync(int shipmentLocationShipmentId, int shipmentLocationLocationId, int shipmentLocationShipmentOrder)
        {
            var response = await mediator.Send(new GetShipmentLocationStatusQuery(shipmentLocationShipmentId, shipmentLocationLocationId, shipmentLocationShipmentOrder));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}', ShipmentLocationLocationId: '{shipmentLocationLocationId}', ShipmentLocationShipmentOrder: '{shipmentLocationShipmentOrder}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-target-location/{shipmentLocationShipmentId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetTargetLocationResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetTargetLocationAsync(int shipmentLocationShipmentId)
        {
            var response = await mediator.Send(new GetTargetLocationQuery(shipmentLocationShipmentId));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-shipment/{shipmentLocationShipmentId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByShipmentResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByShipmentAsync(int shipmentLocationShipmentId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByShipmentQuery(shipmentLocationShipmentId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-location/{shipmentLocationLocationId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByLocationResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByLocationAsync(int shipmentLocationLocationId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByLocationQuery(shipmentLocationLocationId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationLocationId: '{shipmentLocationLocationId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-status/{shipmentLocationLocationStatus}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByStatusResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByStatusAsync(LocationStatus shipmentLocationLocationStatus, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByStatusQuery(shipmentLocationLocationStatus, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationLocationStatus: '{shipmentLocationLocationStatus}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-incomplete-by-shipment/{shipmentLocationShipmentId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetIncompleteByShipmentResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetIncompleteByShipmentAsync(int shipmentLocationShipmentId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetIncompleteByShipmentQuery(shipmentLocationShipmentId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-completed-by-shipment/{shipmentLocationShipmentId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetCompletedByShipmentResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetCompletedByShipmentAsync(int shipmentLocationShipmentId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetCompletedByShipmentQuery(shipmentLocationShipmentId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-with-location/{shipmentLocationsShipmentId:int}/{shipmentLocationsLocationId:int}/{locationsId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetWithLocationResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetWithLocationAsync(int shipmentLocationsShipmentId, int shipmentLocationsLocationId, int locationsId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetWithLocationQuery(shipmentLocationsShipmentId, shipmentLocationsLocationId, locationsId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationsShipmentId: '{shipmentLocationsShipmentId}', ShipmentLocationsLocationId: '{shipmentLocationsLocationId}', LocationsId: '{locationsId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-active-status-view/{shipmentLocationsShipmentId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetActiveStatusViewResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetActiveStatusViewAsync(int shipmentLocationsShipmentId, int shipmentsId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetActiveStatusViewQuery(shipmentLocationsShipmentId, shipmentsId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationsShipmentId: '{shipmentLocationsShipmentId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-target-with-location/{shipmentLocationsShipmentId:int}/{shipmentLocationsLocationId:int}/{locationsId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetTargetWithLocationResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetTargetWithLocationAsync(int shipmentLocationsShipmentId, int shipmentLocationsLocationId, int locationsId)
        {
            var response = await mediator.Send(new GetTargetWithLocationQuery(shipmentLocationsShipmentId, shipmentLocationsLocationId, locationsId));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationsShipmentId: '{shipmentLocationsShipmentId}', ShipmentLocationsLocationId: '{shipmentLocationsLocationId}', LocationsId: '{locationsId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-completed/{shipmentLocationShipmentId:int}/{shipmentLocationLocationId:int}/{shipmentLocationShipmentOrder:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkCompletedAsync(int shipmentLocationShipmentId, int shipmentLocationLocationId, int shipmentLocationShipmentOrder, [FromBody] MarkCompletedRequestDto updateRequest)
        {
            var response = await mediator.Send(new MarkCompletedCommand(shipmentLocationShipmentId, shipmentLocationLocationId, shipmentLocationShipmentOrder, updateRequest));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}', ShipmentLocationLocationId: '{shipmentLocationLocationId}', ShipmentLocationShipmentOrder: '{shipmentLocationShipmentOrder}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-location-status/{shipmentLocationShipmentId:int}/{shipmentLocationLocationId:int}/{shipmentLocationShipmentOrder:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateLocationStatusAsync(int shipmentLocationShipmentId, int shipmentLocationLocationId, int shipmentLocationShipmentOrder, [FromBody] UpdateLocationStatusRequestDto updateRequest)
        {
            var response = await mediator.Send(new UpdateLocationStatusCommand(shipmentLocationShipmentId, shipmentLocationLocationId, shipmentLocationShipmentOrder, updateRequest));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}', ShipmentLocationLocationId: '{shipmentLocationLocationId}', ShipmentLocationShipmentOrder: '{shipmentLocationShipmentOrder}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-arrived/{shipmentLocationShipmentId:int}/{shipmentLocationLocationId:int}/{shipmentLocationShipmentOrder:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkArrivedAsync(int shipmentLocationShipmentId, int shipmentLocationLocationId, int shipmentLocationShipmentOrder, [FromBody] MarkArrivedRequestDto updateRequest)
        {
            var response = await mediator.Send(new MarkArrivedCommand(shipmentLocationShipmentId, shipmentLocationLocationId, shipmentLocationShipmentOrder, updateRequest));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}', ShipmentLocationLocationId: '{shipmentLocationLocationId}', ShipmentLocationShipmentOrder: '{shipmentLocationShipmentOrder}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("cancel-location/{shipmentLocationShipmentId:int}/{shipmentLocationLocationId:int}/{shipmentLocationShipmentOrder:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CancelLocationAsync(int shipmentLocationShipmentId, int shipmentLocationLocationId, int shipmentLocationShipmentOrder, [FromBody] CancelLocationRequestDto updateRequest)
        {
            var response = await mediator.Send(new CancelLocationCommand(shipmentLocationShipmentId, shipmentLocationLocationId, shipmentLocationShipmentOrder, updateRequest));
            if (HandleResponseError(response, logger, "ShipmentLocation", $"ShipmentLocationShipmentId: '{shipmentLocationShipmentId}', ShipmentLocationLocationId: '{shipmentLocationLocationId}', ShipmentLocationShipmentOrder: '{shipmentLocationShipmentOrder}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}