// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Customer;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Customer
{
    public class GetByProfileIdQuery : IRequest<Response<GetByProfileIdResponseDto>>
    {
        public string CustomerProfileId { get; set; }

        public GetByProfileIdQuery(string customerProfileId)
        {
            this.CustomerProfileId = customerProfileId;
        }

        public class GetByProfileIdHandler : IRequestHandler<GetByProfileIdQuery, Response<GetByProfileIdResponseDto>>
        {
            private readonly ILogger<GetByProfileIdHandler> _logger;
            private readonly ICustomerRepository _repository;
            public GetByProfileIdHandler(ILogger<GetByProfileIdHandler> logger, ICustomerRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<GetByProfileIdResponseDto>> Handle(GetByProfileIdQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByProfileIdAsync(request.CustomerProfileId);
                return returnValue.ToResponse();
            }
        }
    }
}