// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Customer;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Customer
{
    public class GetByStateQuery : IRequest<Response<List<GetByStateResponseDto>>>
    {
        public int CustomerStateId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetByStateQuery(int customerStateId, int? pageNumber, int? pageSize)
        {
            this.CustomerStateId = customerStateId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetByStateHandler : IRequestHandler<GetByStateQuery, Response<List<GetByStateResponseDto>>>
        {
            private readonly ILogger<GetByStateHandler> _logger;
            private readonly ICustomerRepository _repository;
            public GetByStateHandler(ILogger<GetByStateHandler> logger, ICustomerRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetByStateResponseDto>>> Handle(GetByStateQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByStateAsync(request.CustomerStateId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}