// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Dtos.Location
{
    public record GetWithStateResponseDto
    {
        public int LocationId { get; init; }
        public string LocationAddress { get; init; }
        public string LocationAlias { get; init; }
        public string StateName { get; init; }
        public string StateShortName { get; init; }
    }
}