-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[SM_INFOS] (
    [GSM_NUMBER],
    [MESSAGE],
    [SMS_DATE],
    [MESSAGE_SID]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_SM_INFO_GSM_NUMBER,
    @PRM_SM_INFO_MESSAGE,
    @PRM_SM_INFO_SMS_DATE,
    @PRM_SM_INFO_MESSAGE_SID
    );