// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Shipment;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Shipment
{
    public class InsertShipmentCommand : IRequest<Response<ShipmentDto>>
    {
        public ShipmentDto request { get; set; }

        public InsertShipmentCommand(ShipmentDto request)
        {
            this.request = request;
        }

        public class InsertShipmentHandler : IRequestHandler<InsertShipmentCommand, Response<ShipmentDto>>
        {
            private readonly ILogger<InsertShipmentHandler> _logger;
            private readonly IShipmentRepository _repository;
            public InsertShipmentHandler(ILogger<InsertShipmentHandler> logger, IShipmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<ShipmentDto>> Handle(InsertShipmentCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.InsertAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}