-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [SMS_OTP_VALIDATIONS] 
	SET [RESULT] = @SM_OTP_VALIDATION_RESULT 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_SM_OTP_VALIDATION_ID