-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [CUSTOMER_ID],
    [CC_OWNER_NAME],
    [CC_CARD_NO],
    [CC_VALID_DATE],
    [CC_CVC],
    [CC_SECURITY_KEY],
    [IS_STORED]
FROM [dbo].[CREDIT_CARDS]
WHERE
    [ID] = @PRM_CREDIT_CARD_ID
    AND [IsDeleted] = 0;