-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[CREDIT_CARDS]
SET
    [CUSTOMER_ID] = @PRM_CREDIT_CARD_CUSTOMER_ID,
    [CC_OWNER_NAME] = @PRM_CREDIT_CARD_CC_OWNER_NAME,
    [CC_CARD_NO] = @PRM_CREDIT_CARD_CC_CARD_NO,
    [CC_VALID_DATE] = @PRM_CREDIT_CARD_CC_VALID_DATE,
    [CC_CVC] = @PRM_CREDIT_CARD_CC_CVC,
    [CC_SECURITY_KEY] = @PRM_CREDIT_CARD_CC_SECURITY_KEY,
    [IS_STORED] = @PRM_CREDIT_CARD_IS_STORED
WHERE
    [ID] = @PRM_CREDIT_CARD_ID
    AND [IsDeleted] = 0;