-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [CUSTOMER_ID],
    [ADDRESS_TEXT],
    [LATITUDE],
    [LONGITUDE],
    [SUITE_NUMBER],
    [ADDRESS_DESCRIPTION],
    [ALIAS_NAME],
    [PLACE_ID],
    [STATE_ID]
FROM [dbo].[LOCATIONS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;