// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Data;
using QuickCode.Freytz.Infrastructure.Data.Extensions;
using QuickCode.Freytz.Infrastructure.Data.Helpers;
using QuickCode.Freytz.MainModule.Application.Dtos.VehicleType;
using QuickCode.Freytz.MainModule.Application.Mappings;
using QuickCode.Freytz.MainModule.Persistence.Sql;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories
{
    public partial class VehicleTypeRepository : BaseRepository, IVehicleTypeRepository
    {
        public async Task<RepoResponse<List<GetVehicleTypesResponseDto>>> GetVehicleTypesAsync()
        {
            return await ExecuteWithExceptionHandling(VehicleTypeCrudSqlBindings.OperationNames.GetVehicleTypes, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.VehicleType.Query.GetVehicleTypes);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetVehicleTypesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in VehicleType");
            });
        }

        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(VehicleTypeCrudSqlBindings.OperationNames.GetActive, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.VehicleType.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in VehicleType");
                }
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string vehicleTypeName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(VehicleTypeCrudSqlBindings.OperationNames.SearchByName, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.VehicleType.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_VEHICLE_TYPE_NAME = vehicleTypeName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in VehicleType");
                }
            });
        }
    }
}