// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Dtos.Payment
{
    public record GetByStatusResponseDto
    {
        public int Id { get; init; }
        public PaymentType PaymentType { get; init; }
        public PaymentStatus PaymentStatus { get; init; }
        public DateTime PaymentTime { get; init; }
        public decimal Amount { get; init; }
        public decimal TotalAmount { get; init; }
        public decimal CapturedAmount { get; init; }
    }
}