// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Dtos.ShipmentPackage
{
    public record ShipmentPackageDto
    {
        public int Id { get; init; }
        public int ShipmentId { get; init; }
        public string PackagePhoto { get; init; }
        public string PackageDescription { get; init; }
        public int RecipientId { get; init; }
        public int SenderId { get; init; }
    }
}