// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Location;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Location
{
    public class DeleteFavoriteCommand : IRequest<Response<int>>
    {
        public int LocationId { get; set; }
        public int LocationCustomerId { get; set; }

        public DeleteFavoriteCommand(int locationId, int locationCustomerId)
        {
            this.LocationId = locationId;
            this.LocationCustomerId = locationCustomerId;
        }

        public class DeleteFavoriteHandler : IRequestHandler<DeleteFavoriteCommand, Response<int>>
        {
            private readonly ILogger<DeleteFavoriteHandler> _logger;
            private readonly ILocationRepository _repository;
            public DeleteFavoriteHandler(ILogger<DeleteFavoriteHandler> logger, ILocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(DeleteFavoriteCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.DeleteFavoriteAsync(request.LocationId, request.LocationCustomerId);
                return returnValue.ToResponse();
            }
        }
    }
}