-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [SHIPMENT_LOCATIONS] 
	SET [IS_COMPLETED] = 1, [LOCATION_STATUS] = 'COMPLETED', [ACTIVITY_TIME] = GETDATE() 
WHERE [IsDeleted] = 0 
	AND [SHIPMENT_ID] = @PRM_SHIPMENT_LOCATION_SHIPMENT_ID 
	AND [LOCATION_ID] = @PRM_SHIPMENT_LOCATION_LOCATION_ID 
	AND [SHIPMENT_ORDER] = @PRM_SHIPMENT_LOCATION_SHIPMENT_ORDER