-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT S.[ID], S.[CUSTOMER_ID], S.[DRIVER_ID], S.[CREATE_DATE], S.[START_DATE], S.[FINISH_DATE], S.[SHIPMENT_STATUS], S.[TOTAL_DISTANCE] 
FROM [SHIPMENTS] S 
WHERE S.[IsDeleted] = 0 
	AND S.[CUSTOMER_ID] = @PRM_SHIPMENT_CUSTOMER_ID 
	AND S.[CREATE_DATE] > DATEADD(DAY, -30,
	GETDATE()) 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 