-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT S.[ID], S.[CUSTOMER_ID], S.[DRIVER_ID], S.[CREATE_DATE], S.[START_DATE], S.[FINISH_DATE], S.[SHIPMENT_STATUS], S.[TOTAL_DISTANCE], S.[STATE_ID] 
FROM [SHIPMENTS] S 
WHERE S.[IsDeleted] = 0 
	AND S.[DRIVER_ID] = @PRM_SHIPMENT_DRIVER_ID 
	AND S.[CREATE_DATE] BETWEEN @PRM_SHIPMENT_CREATE_DATE_From 
	AND @PRM_SHIPMENT_CREATE_DATE_To 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 