-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT S.[ID] AS SHIPMENT_ID,
	S.[CREATE_DATE] AS SHIPMENT_CREATE_DATE,
	S.[SHIPMENT_STATUS], S.[TOTAL_DISTANCE], D.[NAME] AS DRIVER_NAME,
	D.[SURNAME] AS DRIVER_SURNAME 
FROM [SHIPMENTS] S 
	INNER JOIN [DRIVERS] D 
			ON S.[DRIVER_ID] = D.[ID] 
WHERE S.[IsDeleted] = 0 
	AND D.[IsDeleted] = 0 
	AND S.[DRIVER_ID] = @PRM_SHIPMENTS_DRIVER_ID 
	AND D.[ID] = @PRM_DRIVERS_ID 
	AND D.[NAME] LIKE '%' + @PRM_DRIVERS_NAME + '%' 
	AND S.[STATE_ID] = @PRM_SHIPMENTS_STATE_ID 
	AND S.[CREATE_DATE] BETWEEN @PRM_SHIPMENTS_CREATE_DATE_From 
	AND @PRM_SHIPMENTS_CREATE_DATE_To 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 