// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Freytz.MainModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Customer
    {
        public static class Command
        {
            private const string _prefix = "MainModule.Customer.Command";
            private const string _sqlScriptStem = "Customer";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string UpdateStatus => ResourceKey($"{_sqlScriptStem}.UpdateStatus.g.sql");
            public static string Activate => ResourceKey($"{_sqlScriptStem}.Activate.g.sql");
            public static string Deactivate => ResourceKey($"{_sqlScriptStem}.Deactivate.g.sql");
            public static string UpdateDevice => ResourceKey($"{_sqlScriptStem}.UpdateDevice.g.sql");
            public static string UpdateFirebaseId => ResourceKey($"{_sqlScriptStem}.UpdateFirebaseId.g.sql");
            public static string UpdatePassword => ResourceKey($"{_sqlScriptStem}.UpdatePassword.g.sql");
            public static string UpdateProfile => ResourceKey($"{_sqlScriptStem}.UpdateProfile.g.sql");
            public static string UpdateProfileId => ResourceKey($"{_sqlScriptStem}.UpdateProfileId.g.sql");
        }
    }
}