// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Dtos.CustomerLoginAttempt
{
    public record GetByCustomerResponseDto
    {
        public int Id { get; init; }
        public int CustomerId { get; init; }
        public string ClientIp { get; init; }
        public DateTime LoginDate { get; init; }
        public LoginAttemptResult AttemptResult { get; init; }
    }
}