// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Data;
using QuickCode.Freytz.Infrastructure.Data.Extensions;
using QuickCode.Freytz.Infrastructure.Data.Helpers;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverCommission;
using QuickCode.Freytz.MainModule.Application.Mappings;
using QuickCode.Freytz.MainModule.Persistence.Sql;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories
{
    public partial class DriverCommissionRepository : BaseRepository, IDriverCommissionRepository
    {
        public async Task<RepoResponse<GetActiveOnDateResponseDto>> GetActiveOnDateAsync()
        {
            return await ExecuteWithExceptionHandling(DriverCommissionCrudSqlBindings.OperationNames.GetActiveOnDate, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.DriverCommission.Query.GetActiveOnDate);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetActiveOnDateResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in DriverCommission");
            });
        }

        public async Task<RepoResponse<List<GetByDateRangeResponseDto>>> GetByDateRangeAsync(DateTime driverCommissionStartDateFrom, DateTime driverCommissionStartDateTo, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(DriverCommissionCrudSqlBindings.OperationNames.GetByDateRange, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByDateRangeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.DriverCommission.Query.GetByDateRange);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_DRIVER_COMMISSION_START_DATE_From = driverCommissionStartDateFrom,
                        PRM_DRIVER_COMMISSION_START_DATE_To = driverCommissionStartDateTo,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByDateRangeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in DriverCommission");
                }
            });
        }

        public async Task<RepoResponse<List<GetCurrentResponseDto>>> GetCurrentAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(DriverCommissionCrudSqlBindings.OperationNames.GetCurrent, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetCurrentResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.DriverCommission.Query.GetCurrent);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetCurrentResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in DriverCommission");
                }
            });
        }
    }
}