// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Freytz.Domain.Shared.Abstractions;

namespace QuickCode.Freytz.Domain.Shared.Entities;

public class BaseSoftDeletable : ISoftDeletable
{
    public bool IsDeleted { get; set; }

    public DateTime? DeletedOnUtc { get; set; }
}
