// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Data;
using QuickCode.Freytz.Infrastructure.Data.Extensions;
using QuickCode.Freytz.Infrastructure.Data.Helpers;
using QuickCode.Freytz.MainModule.Application.Dtos.CreditCard;
using QuickCode.Freytz.MainModule.Application.Mappings;
using QuickCode.Freytz.MainModule.Persistence.Sql;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories
{
    public partial class CreditCardRepository : BaseRepository, ICreditCardRepository
    {
        public async Task<RepoResponse<List<GetCustomerCreditCardResponseDto>>> GetCustomerCreditCardAsync(int creditCardCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CreditCardCrudSqlBindings.OperationNames.GetCustomerCreditCard, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetCustomerCreditCardResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.CreditCard.Query.GetCustomerCreditCard);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CREDIT_CARD_CUSTOMER_ID = creditCardCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetCustomerCreditCardResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in CreditCard");
                }
            });
        }

        public async Task<RepoResponse<List<GetByCustomerResponseDto>>> GetByCustomerAsync(int creditCardCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CreditCardCrudSqlBindings.OperationNames.GetByCustomer, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCustomerResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.CreditCard.Query.GetByCustomer);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CREDIT_CARD_CUSTOMER_ID = creditCardCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByCustomerResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in CreditCard");
                }
            });
        }

        public async Task<RepoResponse<List<GetStoredByCustomerResponseDto>>> GetStoredByCustomerAsync(int creditCardCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CreditCardCrudSqlBindings.OperationNames.GetStoredByCustomer, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetStoredByCustomerResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.CreditCard.Query.GetStoredByCustomer);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CREDIT_CARD_CUSTOMER_ID = creditCardCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetStoredByCustomerResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in CreditCard");
                }
            });
        }

        public async Task<RepoResponse<List<GetWithCustomerResponseDto>>> GetWithCustomerAsync(int creditCardsCustomerId, int customersId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CreditCardCrudSqlBindings.OperationNames.GetWithCustomer, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetWithCustomerResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.CreditCard.Query.GetWithCustomer);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CREDIT_CARDS_CUSTOMER_ID = creditCardsCustomerId,
                        PRM_CUSTOMERS_ID = customersId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetWithCustomerResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in CreditCard");
                }
            });
        }
    }
}