-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [NAME],
    [SURNAME],
    [COMPANY_NAME],
    [EMAIL],
    [PASSWORD],
    [GSM],
    [PHOTO],
    [PROFILE_ID],
    [DEVICE_TYPE],
    [DEVICE_ID],
    [FIREBASE_ID],
    [STATUS],
    [ADDRESS],
    [STATE_ID]
FROM [dbo].[CUSTOMERS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;