// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.VehicleType;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.VehicleType
{
    public class RestoreCommand : IRequest<Response<int>>
    {
        public int VehicleTypeId { get; set; }
        public RestoreRequestDto UpdateRequest { get; set; }

        public RestoreCommand(int vehicleTypeId, RestoreRequestDto updateRequest)
        {
            this.VehicleTypeId = vehicleTypeId;
            this.UpdateRequest = updateRequest;
        }

        public class RestoreHandler : IRequestHandler<RestoreCommand, Response<int>>
        {
            private readonly ILogger<RestoreHandler> _logger;
            private readonly IVehicleTypeRepository _repository;
            public RestoreHandler(ILogger<RestoreHandler> logger, IVehicleTypeRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(RestoreCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.RestoreAsync(request.VehicleTypeId, request.UpdateRequest);
                return returnValue.ToResponse();
            }
        }
    }
}