// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Freytz.Application.Contracts;
using QcEntity = global::QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Data;
using QuickCode.Freytz.Infrastructure.Data.Extensions;
using QuickCode.Freytz.Infrastructure.Data.Helpers;
using QuickCode.Freytz.MainModule.Application.Dtos.Location;
using QuickCode.Freytz.MainModule.Application.Mappings;
using QuickCode.Freytz.MainModule.Persistence.Sql;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories
{
    public partial class LocationRepository : BaseRepository, ILocationRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public LocationRepository(ILogger<LocationRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "Location")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<LocationDto>> InsertAsync(LocationDto value)
        {
            return await ExecuteWithExceptionHandling(LocationCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Location.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(LocationCrudSqlBindings.ParameterNamePrefix, value, LocationCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.Location>(sql, p);
                return new RepoResponse<LocationDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(LocationDto value)
        {
            return await ExecuteWithExceptionHandling(LocationCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Location.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(LocationCrudSqlBindings.ParameterNamePrefix, value, LocationCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(LocationDto value)
        {
            return await ExecuteWithExceptionHandling(LocationCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Location.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(LocationCrudSqlBindings.ParameterNamePrefix, value, LocationCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<LocationDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(LocationCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Location.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(LocationCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.Location>(sql, p);
                return row == null ? CreateNotFoundResponse<LocationDto>("Not found in Location") : new RepoResponse<LocationDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<LocationDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(LocationCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<LocationDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.Location.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.Location>(sql, p);
                return new RepoResponse<List<LocationDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(LocationCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Location.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}