-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[DRIVER_PAYMENTS]
SET
    [DRIVER_ID] = @PRM_DRIVER_PAYMENT_DRIVER_ID,
    [PAYMENT_ACCOUNT] = @PRM_DRIVER_PAYMENT_PAYMENT_ACCOUNT,
    [PAYMENT_AMOUNT] = @PRM_DRIVER_PAYMENT_PAYMENT_AMOUNT,
    [PAYMENT_DATE] = @PRM_DRIVER_PAYMENT_PAYMENT_DATE,
    [PAYMENT_DESCRIPTION] = @PRM_DRIVER_PAYMENT_PAYMENT_DESCRIPTION,
    [USER_ID] = @PRM_DRIVER_PAYMENT_USER_ID
WHERE
    [ID] = @PRM_DRIVER_PAYMENT_ID
    AND [IsDeleted] = 0;