-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[DRIVER_COMMISSIONS]
SET
    [COMMISSION] = @PRM_DRIVER_COMMISSION_COMMISSION,
    [START_DATE] = @PRM_DRIVER_COMMISSION_START_DATE,
    [END_DATE] = @PRM_DRIVER_COMMISSION_END_DATE
WHERE
    [ID] = @PRM_DRIVER_COMMISSION_ID
    AND [IsDeleted] = 0;