// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.ShipmentLocation
{
    public class GetActiveStatusViewQuery : IRequest<Response<List<GetActiveStatusViewResponseDto>>>
    {
        public int ShipmentLocationsShipmentId { get; set; }
        public int ShipmentsId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetActiveStatusViewQuery(int shipmentLocationsShipmentId, int shipmentsId, int? pageNumber, int? pageSize)
        {
            this.ShipmentLocationsShipmentId = shipmentLocationsShipmentId;
            this.ShipmentsId = shipmentsId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetActiveStatusViewHandler : IRequestHandler<GetActiveStatusViewQuery, Response<List<GetActiveStatusViewResponseDto>>>
        {
            private readonly ILogger<GetActiveStatusViewHandler> _logger;
            private readonly IShipmentLocationRepository _repository;
            public GetActiveStatusViewHandler(ILogger<GetActiveStatusViewHandler> logger, IShipmentLocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetActiveStatusViewResponseDto>>> Handle(GetActiveStatusViewQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetActiveStatusViewAsync(request.ShipmentLocationsShipmentId, request.ShipmentsId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}