// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.ShipmentLocation
{
    public class GetByStatusQuery : IRequest<Response<List<GetByStatusResponseDto>>>
    {
        public LocationStatus ShipmentLocationLocationStatus { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetByStatusQuery(LocationStatus shipmentLocationLocationStatus, int? pageNumber, int? pageSize)
        {
            this.ShipmentLocationLocationStatus = shipmentLocationLocationStatus;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetByStatusHandler : IRequestHandler<GetByStatusQuery, Response<List<GetByStatusResponseDto>>>
        {
            private readonly ILogger<GetByStatusHandler> _logger;
            private readonly IShipmentLocationRepository _repository;
            public GetByStatusHandler(ILogger<GetByStatusHandler> logger, IShipmentLocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetByStatusResponseDto>>> Handle(GetByStatusQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByStatusAsync(request.ShipmentLocationLocationStatus, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}