// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.ShipmentLocation
{
    public class GetIncompleteByShipmentQuery : IRequest<Response<List<GetIncompleteByShipmentResponseDto>>>
    {
        public int ShipmentLocationShipmentId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetIncompleteByShipmentQuery(int shipmentLocationShipmentId, int? pageNumber, int? pageSize)
        {
            this.ShipmentLocationShipmentId = shipmentLocationShipmentId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetIncompleteByShipmentHandler : IRequestHandler<GetIncompleteByShipmentQuery, Response<List<GetIncompleteByShipmentResponseDto>>>
        {
            private readonly ILogger<GetIncompleteByShipmentHandler> _logger;
            private readonly IShipmentLocationRepository _repository;
            public GetIncompleteByShipmentHandler(ILogger<GetIncompleteByShipmentHandler> logger, IShipmentLocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetIncompleteByShipmentResponseDto>>> Handle(GetIncompleteByShipmentQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetIncompleteByShipmentAsync(request.ShipmentLocationShipmentId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}