// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentLocation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.ShipmentLocation
{
    public class GetTargetWithLocationQuery : IRequest<Response<GetTargetWithLocationResponseDto>>
    {
        public int ShipmentLocationsShipmentId { get; set; }
        public int ShipmentLocationsLocationId { get; set; }
        public int LocationsId { get; set; }

        public GetTargetWithLocationQuery(int shipmentLocationsShipmentId, int shipmentLocationsLocationId, int locationsId)
        {
            this.ShipmentLocationsShipmentId = shipmentLocationsShipmentId;
            this.ShipmentLocationsLocationId = shipmentLocationsLocationId;
            this.LocationsId = locationsId;
        }

        public class GetTargetWithLocationHandler : IRequestHandler<GetTargetWithLocationQuery, Response<GetTargetWithLocationResponseDto>>
        {
            private readonly ILogger<GetTargetWithLocationHandler> _logger;
            private readonly IShipmentLocationRepository _repository;
            public GetTargetWithLocationHandler(ILogger<GetTargetWithLocationHandler> logger, IShipmentLocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<GetTargetWithLocationResponseDto>> Handle(GetTargetWithLocationQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetTargetWithLocationAsync(request.ShipmentLocationsShipmentId, request.ShipmentLocationsLocationId, request.LocationsId);
                return returnValue.ToResponse();
            }
        }
    }
}