// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.Freytz.MainModule.Domain;
using QuickCode.Freytz.Domain.Shared.Abstractions;
using QuickCode.Freytz.Domain.Shared.Entities;

namespace QuickCode.Freytz.MainModule.Domain.Entities;

[Table("CREDIT_CARDS")]
public partial class CreditCard : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("CUSTOMER_ID")]
	public int CustomerId { get; set; }
	
	[Column("CC_OWNER_NAME")]
	[StringLength(250)]
	public string CcOwnerName { get; set; }
	
	[Column("CC_CARD_NO")]
	[StringLength(1000)]
	public string CcCardNo { get; set; }
	
	[Column("CC_VALID_DATE")]
	[StringLength(1000)]
	public string CcValidDate { get; set; }
	
	[Column("CC_CVC")]
	[StringLength(1000)]
	public string CcCvc { get; set; }
	
	[Column("CC_SECURITY_KEY")]
	[StringLength(1000)]
	public string CcSecurityKey { get; set; }
	
	[Column("IS_STORED")]
	public bool IsStored { get; set; }
	
	[InverseProperty(nameof(Payment.CreditCard))]
	public virtual ICollection<Payment> Payments { get; } = new List<Payment>();

	[ForeignKey("CustomerId")]
	[InverseProperty(nameof(Customer.CreditCards))]
	public virtual Customer Customer { get; set; } = null!;
}

