// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.Freytz.MainModule.Domain;
using QuickCode.Freytz.Domain.Shared.Abstractions;
using QuickCode.Freytz.Domain.Shared.Entities;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Domain.Entities;

[Table("CUSTOMERS")]
public partial class Customer : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("NAME")]
	[StringLength(250)]
	public string Name { get; set; }
	
	[Column("SURNAME")]
	[StringLength(250)]
	public string Surname { get; set; }
	
	[Column("COMPANY_NAME")]
	[StringLength(1000)]
	public string CompanyName { get; set; }
	
	[Column("EMAIL")]
	[StringLength(500)]
	public string Email { get; set; }
	
	[Column("PASSWORD")]
	[StringLength(1000)]
	public string Password { get; set; }
	
	[Column("GSM")]
	[StringLength(50)]
	public string Gsm { get; set; }
	
	[Column("PHOTO")]
	[StringLength(500)]
	public string Photo { get; set; }
	
	[Column("PROFILE_ID")]
	[StringLength(250)]
	public string ProfileId { get; set; }
	
	[Column("DEVICE_TYPE", TypeName = "nvarchar(50)")]
	public DeviceType DeviceType { get; set; }
	
	[Column("DEVICE_ID")]
	[StringLength(1000)]
	public string DeviceId { get; set; }
	
	[Column("FIREBASE_ID")]
	[StringLength(1000)]
	public string FirebaseId { get; set; }
	
	[Column("STATUS", TypeName = "nvarchar(50)")]
	public SystemStatus? Status { get; set; }
	
	[Column("ADDRESS")]
	[StringLength(int.MaxValue)]
	public string Address { get; set; }
	
	[Column("STATE_ID")]
	public int StateId { get; set; }
	
	[InverseProperty(nameof(CustomerLoginAttempt.Customer))]
	public virtual ICollection<CustomerLoginAttempt> CustomerLoginAttempts { get; } = new List<CustomerLoginAttempt>();

	[InverseProperty(nameof(Location.Customer))]
	public virtual ICollection<Location> Locations { get; } = new List<Location>();

	[InverseProperty(nameof(CreditCard.Customer))]
	public virtual ICollection<CreditCard> CreditCards { get; } = new List<CreditCard>();

	[InverseProperty(nameof(Recipient.Customer))]
	public virtual ICollection<Recipient> Recipients { get; } = new List<Recipient>();

	[InverseProperty(nameof(Sender.Customer))]
	public virtual ICollection<Sender> Senders { get; } = new List<Sender>();

	[InverseProperty(nameof(Shipment.Customer))]
	public virtual ICollection<Shipment> Shipments { get; } = new List<Shipment>();

	[ForeignKey("StateId")]
	[InverseProperty(nameof(State.Customers))]
	public virtual State State { get; set; } = null!;
}

