// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.Freytz.MainModule.Domain;
using QuickCode.Freytz.Domain.Shared.Abstractions;
using QuickCode.Freytz.Domain.Shared.Entities;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Domain.Entities;

[Table("PAYMENTS")]
public partial class Payment : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("PAYMENT_TYPE", TypeName = "nvarchar(50)")]
	public PaymentType PaymentType { get; set; }
	
	[Column("PAYMENT_STATUS", TypeName = "nvarchar(50)")]
	public PaymentStatus PaymentStatus { get; set; }
	
	[Column("PAYMENT_TIME")]
	public DateTime PaymentTime { get; set; }
	
	[Column("AMOUNT")]
	public decimal Amount { get; set; }
	
	[Column("TAX_AMOUNT")]
	public decimal TaxAmount { get; set; }
	
	[Column("TOTAL_AMOUNT")]
	public decimal TotalAmount { get; set; }
	
	[Column("CREDIT_CARD_ID")]
	public int CreditCardId { get; set; }
	
	[Column("CC_PAYMENT_TIME")]
	public DateTime CcPaymentTime { get; set; }
	
	[Column("CC_REF_NO")]
	[StringLength(250)]
	public string CcRefNo { get; set; }
	
	[Column("PAYMENT_REF")]
	[StringLength(250)]
	public string PaymentRef { get; set; }
	
	[Column("CAPTURED_AMOUNT")]
	public decimal CapturedAmount { get; set; }
	
	[InverseProperty(nameof(Shipment.Payment))]
	public virtual ICollection<Shipment> Shipments { get; } = new List<Shipment>();

	[ForeignKey("CreditCardId")]
	[InverseProperty(nameof(CreditCard.Payments))]
	public virtual CreditCard CreditCard { get; set; } = null!;
}

