// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.Freytz.MainModule.Domain;
using QuickCode.Freytz.Domain.Shared.Abstractions;
using QuickCode.Freytz.Domain.Shared.Entities;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Domain.Entities;

[Table("SHIPMENTS")]
public partial class Shipment : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("CUSTOMER_ID")]
	public int CustomerId { get; set; }
	
	[Column("DRIVER_ID")]
	public int DriverId { get; set; }
	
	[Column("SHIPMENT_TYPE", TypeName = "nvarchar(50)")]
	public ShipmentType ShipmentType { get; set; }
	
	[Column("CREATE_DATE")]
	public DateTime CreateDate { get; set; }
	
	[Column("START_DATE")]
	public DateTime StartDate { get; set; }
	
	[Column("FINISH_DATE")]
	public DateTime FinishDate { get; set; }
	
	[Column("PLANNED_ARRIVE_TIME")]
	public DateTime PlannedArriveTime { get; set; }
	
	[Column("SHIPMENT_STATUS", TypeName = "nvarchar(50)")]
	public ShipmentStatus ShipmentStatus { get; set; }
	
	[Column("PAYMENT_ID")]
	public int PaymentId { get; set; }
	
	[Column("PLANNED_DURATION")]
	[StringLength(50)]
	public string PlannedDuration { get; set; }
	
	[Column("TOTAL_DISTANCE")]
	public decimal TotalDistance { get; set; }
	
	[Column("DRIVER_INSTRUCTIONS")]
	[StringLength(int.MaxValue)]
	public string DriverInstructions { get; set; }
	
	[Column("STATE_ID")]
	public int StateId { get; set; }
	
	[Column("VEHICLE_TYPE_ID")]
	public int VehicleTypeId { get; set; }
	
	[InverseProperty(nameof(DriverPaymentShipment.Shipment))]
	public virtual ICollection<DriverPaymentShipment> DriverPaymentShipments { get; } = new List<DriverPaymentShipment>();

	[InverseProperty(nameof(ShipmentLocation.Shipment))]
	public virtual ICollection<ShipmentLocation> ShipmentLocations { get; } = new List<ShipmentLocation>();

	[InverseProperty(nameof(ShipmentPackage.Shipment))]
	public virtual ICollection<ShipmentPackage> ShipmentPackages { get; } = new List<ShipmentPackage>();

	[ForeignKey("CustomerId")]
	[InverseProperty(nameof(Customer.Shipments))]
	public virtual Customer Customer { get; set; } = null!;

	[ForeignKey("DriverId")]
	[InverseProperty(nameof(Driver.Shipments))]
	public virtual Driver Driver { get; set; } = null!;

	[ForeignKey("PaymentId")]
	[InverseProperty(nameof(Payment.Shipments))]
	public virtual Payment Payment { get; set; } = null!;

	[ForeignKey("StateId")]
	[InverseProperty(nameof(State.Shipments))]
	public virtual State State { get; set; } = null!;

	[ForeignKey("VehicleTypeId")]
	[InverseProperty(nameof(VehicleType.Shipments))]
	public virtual VehicleType VehicleType { get; set; } = null!;
}

