// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.Freytz.MainModule.Domain;
using QuickCode.Freytz.Domain.Shared.Abstractions;
using QuickCode.Freytz.Domain.Shared.Entities;

namespace QuickCode.Freytz.MainModule.Domain.Entities;

[Table("SHIPMENT_PACKAGES")]
public partial class ShipmentPackage : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("SHIPMENT_ID")]
	public int ShipmentId { get; set; }
	
	[Column("PACKAGE_PHOTO")]
	[StringLength(500)]
	public string PackagePhoto { get; set; }
	
	[Column("PACKAGE_DESCRIPTION")]
	[StringLength(1000)]
	public string PackageDescription { get; set; }
	
	[Column("RECIPIENT_ID")]
	public int RecipientId { get; set; }
	
	[Column("SENDER_ID")]
	public int SenderId { get; set; }
	
	[ForeignKey("ShipmentId")]
	[InverseProperty(nameof(Shipment.ShipmentPackages))]
	public virtual Shipment Shipment { get; set; } = null!;

	[ForeignKey("RecipientId")]
	[InverseProperty(nameof(Recipient.ShipmentPackages))]
	public virtual Recipient Recipient { get; set; } = null!;

	[ForeignKey("SenderId")]
	[InverseProperty(nameof(Sender.ShipmentPackages))]
	public virtual Sender Sender { get; set; } = null!;
}

