// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.Freytz.MainModule.Domain;
using QuickCode.Freytz.Domain.Shared.Abstractions;
using QuickCode.Freytz.Domain.Shared.Entities;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Domain.Entities;

[Table("STATES")]
public partial class State : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("NAME")]
	[StringLength(250)]
	public string Name { get; set; }
	
	[Column("SHORT_NAME")]
	[StringLength(50)]
	public string ShortName { get; set; }
	
	[Column("TIME_ZONE")]
	[StringLength(250)]
	public string TimeZone { get; set; }
	
	[Column("STATUS", TypeName = "nvarchar(50)")]
	public SystemStatus Status { get; set; }
	
	[InverseProperty(nameof(Customer.State))]
	public virtual ICollection<Customer> Customers { get; } = new List<Customer>();

	[InverseProperty(nameof(Driver.State))]
	public virtual ICollection<Driver> Drivers { get; } = new List<Driver>();

	[InverseProperty(nameof(Location.State))]
	public virtual ICollection<Location> Locations { get; } = new List<Location>();

	[InverseProperty(nameof(PriceMatrix.State))]
	public virtual ICollection<PriceMatrix> PriceMatrices { get; } = new List<PriceMatrix>();

	[InverseProperty(nameof(Shipment.State))]
	public virtual ICollection<Shipment> Shipments { get; } = new List<Shipment>();

	[InverseProperty(nameof(UserState.State))]
	public virtual ICollection<UserState> UserStates { get; } = new List<UserState>();
}

