// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.Freytz.MainModule.Domain;
using QuickCode.Freytz.Domain.Shared.Abstractions;
using QuickCode.Freytz.Domain.Shared.Entities;

namespace QuickCode.Freytz.MainModule.Domain.Entities;

[Table("VEHICLE_TYPES")]
public partial class VehicleType : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("NAME")]
	[StringLength(250)]
	public string Name { get; set; }
	
	[Column("CAPACITY")]
	public int Capacity { get; set; }
	
	[Column("IS_DELETED")]
	public bool IsDeleted { get; set; }
	
	[Column("ORDER")]
	public int Order { get; set; }
	
	[Column("IMAGE_PATH")]
	[StringLength(500)]
	public string ImagePath { get; set; }
	
	[InverseProperty(nameof(Driver.VehicleType))]
	public virtual ICollection<Driver> Drivers { get; } = new List<Driver>();

	[InverseProperty(nameof(PriceMatrix.VehicleType))]
	public virtual ICollection<PriceMatrix> PriceMatrices { get; } = new List<PriceMatrix>();

	[InverseProperty(nameof(Shipment.VehicleType))]
	public virtual ICollection<Shipment> Shipments { get; } = new List<Shipment>();
}

