-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [NAME],
    [CAPACITY],
    [IS_DELETED],
    [ORDER],
    [IMAGE_PATH]
FROM [dbo].[VEHICLE_TYPES]
WHERE
    [ID] = @PRM_VEHICLE_TYPE_ID
    AND [IS_DELETED] = 0;