-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [NAME],
    [SHORT_NAME],
    [TIME_ZONE],
    [STATUS]
FROM [dbo].[STATES]
WHERE
    [ID] = @PRM_STATE_ID
    AND [IsDeleted] = 0;