// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Dtos.Driver;
using System.Threading.Tasks;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Interfaces.Repositories
{
    public partial interface IDriverRepository : IBaseRepository<DriverDto>
    {
        Task<RepoResponse<DriverDto>> GetByPkAsync(int id);
        Task<RepoResponse<DriverLoginResponseDto>> DriverLoginAsync(string driverEmail, string driverPassword);
        Task<RepoResponse<GetByEmailResponseDto>> GetByEmailAsync(string driverEmail);
        Task<RepoResponse<GetByGsmResponseDto>> GetByGsmAsync(string driverGsm);
        Task<RepoResponse<GetPasswordByGsmResponseDto>> GetPasswordByGsmAsync(string driverGsm);
        Task<RepoResponse<GetPasswordByEmailResponseDto>> GetPasswordByEmailAsync(string driverEmail);
        Task<RepoResponse<GetPhotoResponseDto>> GetPhotoAsync(int driverId);
        Task<RepoResponse<GetMaxDistanceResponseDto>> GetMaxDistanceAsync(int driverId);
        Task<RepoResponse<GetDriverStatusResponseDto>> GetDriverStatusAsync(int driverId);
        Task<RepoResponse<bool>> CheckDriverDeviceAsync(DeviceType driverDeviceType, string driverDeviceId);
        Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(SystemStatus driverStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByDriverStatusResponseDto>>> GetByDriverStatusAsync(DriverStatus driverDriverStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetAvailableResponseDto>>> GetAvailableAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<FindAvailableByVehicleResponseDto>>> FindAvailableByVehicleAsync(int driverVehicleTypeId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByStateResponseDto>>> GetByStateAsync(int driverStateId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByVehicleTypeResponseDto>>> GetByVehicleTypeAsync(int driverVehicleTypeId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string driverName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWithVehicleTypeResponseDto>>> GetWithVehicleTypeAsync(int driversVehicleTypeId, int vehicleTypesId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWithStateResponseDto>>> GetWithStateAsync(int driversStateId, int statesId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetAvailableWithLocationResponseDto>>> GetAvailableWithLocationAsync(int driversLastLocationId, int driverLocationsId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<long>> GetActiveCountAsync();
        Task<RepoResponse<long>> GetAvailableCountAsync();
        Task<RepoResponse<bool>> ExistsByEmailAsync(string driverEmail);
        Task<RepoResponse<bool>> ExistsByGsmAsync(string driverGsm);
        Task<RepoResponse<int>> UpdateDriverStatusAsync(int driverId, UpdateDriverStatusRequestDto updateRequest);
        Task<RepoResponse<int>> SetAvailableAsync(int driverId, SetAvailableRequestDto updateRequest);
        Task<RepoResponse<int>> SetBusyAsync(int driverId, SetBusyRequestDto updateRequest);
        Task<RepoResponse<int>> UpdateStatusAsync(int driverId, UpdateStatusRequestDto updateRequest);
        Task<RepoResponse<int>> UpdateDeviceAsync(int driverId, UpdateDeviceRequestDto updateRequest);
        Task<RepoResponse<int>> UpdateFirebaseIdAsync(int driverId, UpdateFirebaseIdRequestDto updateRequest);
        Task<RepoResponse<int>> UpdatePasswordAsync(int driverId, UpdatePasswordRequestDto updateRequest);
        Task<RepoResponse<int>> UpdateProfileAsync(int driverId, UpdateProfileRequestDto updateRequest);
        Task<RepoResponse<int>> UpdatePhotoAsync(int driverId, UpdatePhotoRequestDto updateRequest);
        Task<RepoResponse<int>> UpdateMaxDistanceAsync(int driverId, UpdateMaxDistanceRequestDto updateRequest);
        Task<RepoResponse<int>> UpdateLastLocationAsync(int driverId, UpdateLastLocationRequestDto updateRequest);
        Task<RepoResponse<int>> UpdatePaymentAccountAsync(int driverId, UpdatePaymentAccountRequestDto updateRequest);
    }
}