// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverLocation;
using System.Threading.Tasks;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Interfaces.Repositories
{
    public partial interface IDriverLocationRepository : IBaseRepository<DriverLocationDto>
    {
        Task<RepoResponse<DriverLocationDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByDriverResponseDto>>> GetByDriverAsync(int driverLocationDriverId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRecentByDriverResponseDto>>> GetRecentByDriverAsync(int driverLocationDriverId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetLatestByDriverResponseDto>> GetLatestByDriverAsync(int driverLocationDriverId);
        Task<RepoResponse<List<GetWithDriverResponseDto>>> GetWithDriverAsync(int driverLocationsDriverId, int driversId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<long>> GetTodayCountAsync();
    }
}