// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Dtos.Payment;
using System.Threading.Tasks;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Interfaces.Repositories
{
    public partial interface IPaymentRepository : IBaseRepository<PaymentDto>
    {
        Task<RepoResponse<PaymentDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(PaymentStatus paymentPaymentStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByTypeResponseDto>>> GetByTypeAsync(PaymentType paymentPaymentType, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPendingResponseDto>>> GetPendingAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByCreditCardResponseDto>>> GetByCreditCardAsync(int paymentCreditCardId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByDateRangeResponseDto>>> GetByDateRangeAsync(DateTime paymentPaymentTimeFrom, DateTime paymentPaymentTimeTo, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRecentResponseDto>>> GetRecentAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetDailySummaryResponseDto>> GetDailySummaryAsync();
        Task<RepoResponse<GetMonthlySummaryResponseDto>> GetMonthlySummaryAsync();
        Task<RepoResponse<long>> GetCapturedCountAsync();
        Task<RepoResponse<int>> UpdateStatusAsync(int paymentId, UpdateStatusRequestDto updateRequest);
        Task<RepoResponse<int>> MarkCapturedAsync(int paymentId, MarkCapturedRequestDto updateRequest);
        Task<RepoResponse<int>> MarkFailedAsync(int paymentId, MarkFailedRequestDto updateRequest);
        Task<RepoResponse<int>> SetPaymentRefAsync(int paymentId, SetPaymentRefRequestDto updateRequest);
    }
}