// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Dtos.ShipmentPackage;
using System.Threading.Tasks;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Interfaces.Repositories
{
    public partial interface IShipmentPackageRepository : IBaseRepository<ShipmentPackageDto>
    {
        Task<RepoResponse<ShipmentPackageDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetPackagePhotoResponseDto>> GetPackagePhotoAsync(int shipmentPackageId, int shipmentPackageShipmentId);
        Task<RepoResponse<List<GetByShipmentResponseDto>>> GetByShipmentAsync(int shipmentPackageShipmentId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByRecipientResponseDto>>> GetByRecipientAsync(int shipmentPackageRecipientId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetBySenderResponseDto>>> GetBySenderAsync(int shipmentPackageSenderId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWithRecipientResponseDto>>> GetWithRecipientAsync(int shipmentPackagesRecipientId, int recipientsId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWithSenderResponseDto>>> GetWithSenderAsync(int shipmentPackagesSenderId, int sendersId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWithShipmentResponseDto>>> GetWithShipmentAsync(int shipmentPackagesShipmentId, int shipmentsId, int? pageNumber = null, int? pageSize = null);
    }
}