// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Dtos.SmOtp;
using System.Threading.Tasks;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Interfaces.Repositories
{
    public partial interface ISmOtpRepository : IBaseRepository<SmOtpDto>
    {
        Task<RepoResponse<SmOtpDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetLastSmsOtpResponseDto>> GetLastSmsOtpAsync(string smOtpGsmNumber);
        Task<RepoResponse<List<GetByGsmResponseDto>>> GetByGsmAsync(string smOtpGsmNumber, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetLatestByGsmResponseDto>> GetLatestByGsmAsync(string smOtpGsmNumber);
        Task<RepoResponse<List<GetRecentResponseDto>>> GetRecentAsync(int? pageNumber = null, int? pageSize = null);
    }
}