// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Dtos.State;
using System.Threading.Tasks;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Interfaces.Repositories
{
    public partial interface IStateRepository : IBaseRepository<StateDto>
    {
        Task<RepoResponse<StateDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetAvailableStatesResponseDto>>> GetAvailableStatesAsync();
        Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(SystemStatus stateStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string stateName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetByShortNameResponseDto>> GetByShortNameAsync(string stateShortName);
        Task<RepoResponse<int>> DeactivateAsync(int stateId, DeactivateRequestDto updateRequest);
        Task<RepoResponse<int>> ActivateAsync(int stateId, ActivateRequestDto updateRequest);
    }
}