// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Dtos.UserState;
using System.Threading.Tasks;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Interfaces.Repositories
{
    public partial interface IUserStateRepository : IBaseRepository<UserStateDto>
    {
        Task<RepoResponse<UserStateDto>> GetByPkAsync(int stateId, int userId);
        Task<RepoResponse<List<GetByUserResponseDto>>> GetByUserAsync(int userStateUserId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByStateResponseDto>>> GetByStateAsync(int userStateStateId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWithStateResponseDto>>> GetWithStateAsync(int userStatesStateId, int statesId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<bool>> ExistsLinkAsync(int userStateStateId, int userStateUserId);
        Task<RepoResponse<int>> UnlinkAsync(int userStateStateId, int userStateUserId);
    }
}