// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Freytz.Infrastructure.Data;
using QuickCode.Freytz.Infrastructure.Data.Extensions;
using QuickCode.Freytz.Infrastructure.Data.Helpers;
using QuickCode.Freytz.MainModule.Application.Dtos.SmOtpValidation;
using QuickCode.Freytz.MainModule.Application.Mappings;
using QuickCode.Freytz.MainModule.Persistence.Sql;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Persistence.Repositories
{
    public partial class SmOtpValidationRepository : BaseRepository, ISmOtpValidationRepository
    {
        public async Task<RepoResponse<int>> IncrementTryAsync(int smOtpValidationId, IncrementTryRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(SmOtpValidationCrudSqlBindings.OperationNames.IncrementTry, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SmOtpValidation.Command.IncrementTry);
                var parameters = new
                {
                    SM_OTP_VALIDATION_TRY_COUNT = updateRequest.SmOtpValidationTryCount,
                    PRM_SM_OTP_VALIDATION_ID = smOtpValidationId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> SetResultAsync(int smOtpValidationId, SetResultRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(SmOtpValidationCrudSqlBindings.OperationNames.SetResult, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SmOtpValidation.Command.SetResult);
                var parameters = new
                {
                    SM_OTP_VALIDATION_RESULT = updateRequest.SmOtpValidationResult,
                    PRM_SM_OTP_VALIDATION_ID = smOtpValidationId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> MarkSuccessAsync(int smOtpValidationId, MarkSuccessRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(SmOtpValidationCrudSqlBindings.OperationNames.MarkSuccess, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SmOtpValidation.Command.MarkSuccess);
                var parameters = new
                {
                    PRM_SM_OTP_VALIDATION_ID = smOtpValidationId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> MarkFailedAsync(int smOtpValidationId, MarkFailedRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(SmOtpValidationCrudSqlBindings.OperationNames.MarkFailed, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SmOtpValidation.Command.MarkFailed);
                var parameters = new
                {
                    PRM_SM_OTP_VALIDATION_ID = smOtpValidationId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}