// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Freytz.MainModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class SmOtpValidation
    {
        public static class Query
        {
            private const string _prefix = "MainModule.SmOtpValidation.Query";
            private const string _sqlScriptStem = "SmOtpValidation";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetByGsm => ResourceKey($"{_sqlScriptStem}.GetByGsm.g.sql");
            public static string GetByOtp => ResourceKey($"{_sqlScriptStem}.GetByOtp.g.sql");
            public static string GetWithOtp => ResourceKey($"{_sqlScriptStem}.GetWithOtp.g.sql");
            public static string GetFailedCount => ResourceKey($"{_sqlScriptStem}.GetFailedCount.g.sql");
        }
    }
}