// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Driver;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Driver
{
    public class GetActiveCountQuery : IRequest<Response<long>>
    {
        public GetActiveCountQuery()
        {
        }

        public class GetActiveCountHandler : IRequestHandler<GetActiveCountQuery, Response<long>>
        {
            private readonly ILogger<GetActiveCountHandler> _logger;
            private readonly IDriverRepository _repository;
            public GetActiveCountHandler(ILogger<GetActiveCountHandler> logger, IDriverRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<long>> Handle(GetActiveCountQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetActiveCountAsync();
                return returnValue.ToResponse();
            }
        }
    }
}