// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Driver;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Driver
{
    public class GetByDriverStatusQuery : IRequest<Response<List<GetByDriverStatusResponseDto>>>
    {
        public DriverStatus DriverDriverStatus { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetByDriverStatusQuery(DriverStatus driverDriverStatus, int? pageNumber, int? pageSize)
        {
            this.DriverDriverStatus = driverDriverStatus;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetByDriverStatusHandler : IRequestHandler<GetByDriverStatusQuery, Response<List<GetByDriverStatusResponseDto>>>
        {
            private readonly ILogger<GetByDriverStatusHandler> _logger;
            private readonly IDriverRepository _repository;
            public GetByDriverStatusHandler(ILogger<GetByDriverStatusHandler> logger, IDriverRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetByDriverStatusResponseDto>>> Handle(GetByDriverStatusQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByDriverStatusAsync(request.DriverDriverStatus, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}