// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Driver;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Driver
{
    public class GetWithVehicleTypeQuery : IRequest<Response<List<GetWithVehicleTypeResponseDto>>>
    {
        public int DriversVehicleTypeId { get; set; }
        public int VehicleTypesId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetWithVehicleTypeQuery(int driversVehicleTypeId, int vehicleTypesId, int? pageNumber, int? pageSize)
        {
            this.DriversVehicleTypeId = driversVehicleTypeId;
            this.VehicleTypesId = vehicleTypesId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetWithVehicleTypeHandler : IRequestHandler<GetWithVehicleTypeQuery, Response<List<GetWithVehicleTypeResponseDto>>>
        {
            private readonly ILogger<GetWithVehicleTypeHandler> _logger;
            private readonly IDriverRepository _repository;
            public GetWithVehicleTypeHandler(ILogger<GetWithVehicleTypeHandler> logger, IDriverRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetWithVehicleTypeResponseDto>>> Handle(GetWithVehicleTypeQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetWithVehicleTypeAsync(request.DriversVehicleTypeId, request.VehicleTypesId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}