// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Driver;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Driver
{
    public class SearchByNameQuery : IRequest<Response<List<SearchByNameResponseDto>>>
    {
        public string DriverName { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public SearchByNameQuery(string driverName, int? pageNumber, int? pageSize)
        {
            this.DriverName = driverName;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class SearchByNameHandler : IRequestHandler<SearchByNameQuery, Response<List<SearchByNameResponseDto>>>
        {
            private readonly ILogger<SearchByNameHandler> _logger;
            private readonly IDriverRepository _repository;
            public SearchByNameHandler(ILogger<SearchByNameHandler> logger, IDriverRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<SearchByNameResponseDto>>> Handle(SearchByNameQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.SearchByNameAsync(request.DriverName, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}