// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Recipient;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Recipient
{
    public class DeleteCustomerRecipientCommand : IRequest<Response<int>>
    {
        public int RecipientId { get; set; }
        public int RecipientCustomerId { get; set; }

        public DeleteCustomerRecipientCommand(int recipientId, int recipientCustomerId)
        {
            this.RecipientId = recipientId;
            this.RecipientCustomerId = recipientCustomerId;
        }

        public class DeleteCustomerRecipientHandler : IRequestHandler<DeleteCustomerRecipientCommand, Response<int>>
        {
            private readonly ILogger<DeleteCustomerRecipientHandler> _logger;
            private readonly IRecipientRepository _repository;
            public DeleteCustomerRecipientHandler(ILogger<DeleteCustomerRecipientHandler> logger, IRecipientRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(DeleteCustomerRecipientCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.DeleteCustomerRecipientAsync(request.RecipientId, request.RecipientCustomerId);
                return returnValue.ToResponse();
            }
        }
    }
}