-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[SM_OTPS]
SET
    [GSM_NUMBER] = @PRM_SM_OTP_GSM_NUMBER,
    [SMS_CODE] = @PRM_SM_OTP_SMS_CODE,
    [SMS_DATE] = @PRM_SM_OTP_SMS_DATE,
    [SMS_VALID_SECOND] = @PRM_SM_OTP_SMS_VALID_SECOND,
    [MESSAGE_SID] = @PRM_SM_OTP_MESSAGE_SID
WHERE
    [ID] = @PRM_SM_OTP_ID
    AND [IsDeleted] = 0;