-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CASE WHEN EXISTS (
SELECT 1 
FROM [CUSTOMERS] C 
WHERE C.[IsDeleted] = 0 
	AND C.[GSM] = @PRM_CUSTOMER_GSM ) THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END