// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Freytz.MainModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Customer
    {
        public static class Query
        {
            private const string _prefix = "MainModule.Customer.Query";
            private const string _sqlScriptStem = "Customer";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string CustomerLogin => ResourceKey($"{_sqlScriptStem}.CustomerLogin.g.sql");
            public static string GetByEmail => ResourceKey($"{_sqlScriptStem}.GetByEmail.g.sql");
            public static string GetByGsm => ResourceKey($"{_sqlScriptStem}.GetByGsm.g.sql");
            public static string GetPasswordByGsm => ResourceKey($"{_sqlScriptStem}.GetPasswordByGsm.g.sql");
            public static string GetPasswordByEmail => ResourceKey($"{_sqlScriptStem}.GetPasswordByEmail.g.sql");
            public static string GetByProfileId => ResourceKey($"{_sqlScriptStem}.GetByProfileId.g.sql");
            public static string GetPhoto => ResourceKey($"{_sqlScriptStem}.GetPhoto.g.sql");
            public static string CheckCustomerDevice => ResourceKey($"{_sqlScriptStem}.CheckCustomerDevice.g.sql");
            public static string GetByStatus => ResourceKey($"{_sqlScriptStem}.GetByStatus.g.sql");
            public static string GetActive => ResourceKey($"{_sqlScriptStem}.GetActive.g.sql");
            public static string GetByState => ResourceKey($"{_sqlScriptStem}.GetByState.g.sql");
            public static string GetByDeviceType => ResourceKey($"{_sqlScriptStem}.GetByDeviceType.g.sql");
            public static string SearchByName => ResourceKey($"{_sqlScriptStem}.SearchByName.g.sql");
            public static string GetWithState => ResourceKey($"{_sqlScriptStem}.GetWithState.g.sql");
            public static string ExistsByEmail => ResourceKey($"{_sqlScriptStem}.ExistsByEmail.g.sql");
            public static string ExistsByGsm => ResourceKey($"{_sqlScriptStem}.ExistsByGsm.g.sql");
            public static string GetActiveCount => ResourceKey($"{_sqlScriptStem}.GetActiveCount.g.sql");
        }
    }
}