// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Sender;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Sender
{
    public class GetCustomerSenderQuery : IRequest<Response<List<GetCustomerSenderResponseDto>>>
    {
        public int SenderCustomerId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetCustomerSenderQuery(int senderCustomerId, int? pageNumber, int? pageSize)
        {
            this.SenderCustomerId = senderCustomerId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetCustomerSenderHandler : IRequestHandler<GetCustomerSenderQuery, Response<List<GetCustomerSenderResponseDto>>>
        {
            private readonly ILogger<GetCustomerSenderHandler> _logger;
            private readonly ISenderRepository _repository;
            public GetCustomerSenderHandler(ILogger<GetCustomerSenderHandler> logger, ISenderRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetCustomerSenderResponseDto>>> Handle(GetCustomerSenderQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetCustomerSenderAsync(request.SenderCustomerId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}