// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Sender;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Sender
{
    public class TotalCountSenderQuery : IRequest<Response<int>>
    {
        public TotalCountSenderQuery()
        {
        }

        public class TotalCountSenderHandler : IRequestHandler<TotalCountSenderQuery, Response<int>>
        {
            private readonly ILogger<TotalCountSenderHandler> _logger;
            private readonly ISenderRepository _repository;
            public TotalCountSenderHandler(ILogger<TotalCountSenderHandler> logger, ISenderRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(TotalCountSenderQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.CountAsync();
                return returnValue.ToResponse();
            }
        }
    }
}