// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Location;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Location
{
    public class GetCustomerLocationQuery : IRequest<Response<List<GetCustomerLocationResponseDto>>>
    {
        public int LocationCustomerId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetCustomerLocationQuery(int locationCustomerId, int? pageNumber, int? pageSize)
        {
            this.LocationCustomerId = locationCustomerId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetCustomerLocationHandler : IRequestHandler<GetCustomerLocationQuery, Response<List<GetCustomerLocationResponseDto>>>
        {
            private readonly ILogger<GetCustomerLocationHandler> _logger;
            private readonly ILocationRepository _repository;
            public GetCustomerLocationHandler(ILogger<GetCustomerLocationHandler> logger, ILocationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetCustomerLocationResponseDto>>> Handle(GetCustomerLocationQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetCustomerLocationAsync(request.LocationCustomerId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}