// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.VehicleType;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.VehicleType
{
    public class GetItemVehicleTypeQuery : IRequest<Response<VehicleTypeDto>>
    {
        public int Id { get; set; }

        public GetItemVehicleTypeQuery(int id)
        {
            this.Id = id;
        }

        public class GetItemVehicleTypeHandler : IRequestHandler<GetItemVehicleTypeQuery, Response<VehicleTypeDto>>
        {
            private readonly ILogger<GetItemVehicleTypeHandler> _logger;
            private readonly IVehicleTypeRepository _repository;
            public GetItemVehicleTypeHandler(ILogger<GetItemVehicleTypeHandler> logger, IVehicleTypeRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<VehicleTypeDto>> Handle(GetItemVehicleTypeQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.Id);
                return returnValue.ToResponse();
            }
        }
    }
}