// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Freytz.MainModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Shipment
    {
        public static class Command
        {
            private const string _prefix = "MainModule.Shipment.Command";
            private const string _sqlScriptStem = "Shipment";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string UpdateStatus => ResourceKey($"{_sqlScriptStem}.UpdateStatus.g.sql");
            public static string UpdateShipmentStatus => ResourceKey($"{_sqlScriptStem}.UpdateShipmentStatus.g.sql");
            public static string AssignDriver => ResourceKey($"{_sqlScriptStem}.AssignDriver.g.sql");
            public static string Start => ResourceKey($"{_sqlScriptStem}.Start.g.sql");
            public static string Complete => ResourceKey($"{_sqlScriptStem}.Complete.g.sql");
            public static string Cancel => ResourceKey($"{_sqlScriptStem}.Cancel.g.sql");
            public static string SetPayment => ResourceKey($"{_sqlScriptStem}.SetPayment.g.sql");
        }
    }
}