// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.Sender;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.Sender
{
    public class DeleteCustomerSenderCommand : IRequest<Response<int>>
    {
        public int SenderId { get; set; }
        public int SenderCustomerId { get; set; }

        public DeleteCustomerSenderCommand(int senderId, int senderCustomerId)
        {
            this.SenderId = senderId;
            this.SenderCustomerId = senderCustomerId;
        }

        public class DeleteCustomerSenderHandler : IRequestHandler<DeleteCustomerSenderCommand, Response<int>>
        {
            private readonly ILogger<DeleteCustomerSenderHandler> _logger;
            private readonly ISenderRepository _repository;
            public DeleteCustomerSenderHandler(ILogger<DeleteCustomerSenderHandler> logger, ISenderRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(DeleteCustomerSenderCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.DeleteCustomerSenderAsync(request.SenderId, request.SenderCustomerId);
                return returnValue.ToResponse();
            }
        }
    }
}