-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[CUSTOMER_LOGIN_ATTEMPTS]
SET
    [CUSTOMER_ID] = @PRM_CUSTOMER_LOGIN_ATTEMPT_CUSTOMER_ID,
    [CLIENT_IP] = @PRM_CUSTOMER_LOGIN_ATTEMPT_CLIENT_IP,
    [LOGIN_DATE] = @PRM_CUSTOMER_LOGIN_ATTEMPT_LOGIN_DATE,
    [ATTEMPT_RESULT] = @PRM_CUSTOMER_LOGIN_ATTEMPT_ATTEMPT_RESULT
WHERE
    [ID] = @PRM_CUSTOMER_LOGIN_ATTEMPT_ID
    AND [IsDeleted] = 0;