-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [DRIVER_PAYMENT_ID],
    [SHIPMENT_ID]
FROM [dbo].[DRIVER_PAYMENT_SHIPMENTS]
WHERE
    [DRIVER_PAYMENT_ID] = @PRM_DRIVER_PAYMENT_SHIPMENT_DRIVER_PAYMENT_ID AND
    [SHIPMENT_ID] = @PRM_DRIVER_PAYMENT_SHIPMENT_SHIPMENT_ID
    AND EXISTS (
    SELECT 1
    FROM [dbo].[DRIVER_PAYMENTS] qc_sd_p
    WHERE qc_sd_p.[ID] = [dbo].[DRIVER_PAYMENT_SHIPMENTS].[DRIVER_PAYMENT_ID]
      AND qc_sd_p.[IsDeleted] = 0)
    AND EXISTS (
    SELECT 1
    FROM [dbo].[SHIPMENTS] qc_sd_p
    WHERE qc_sd_p.[ID] = [dbo].[DRIVER_PAYMENT_SHIPMENTS].[SHIPMENT_ID]
      AND qc_sd_p.[IsDeleted] = 0);