// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Freytz.MainModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class VehicleType
    {
        public static class Command
        {
            private const string _prefix = "MainModule.VehicleType.Command";
            private const string _sqlScriptStem = "VehicleType";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string SoftDelete => ResourceKey($"{_sqlScriptStem}.SoftDelete.g.sql");
            public static string Restore => ResourceKey($"{_sqlScriptStem}.Restore.g.sql");
        }
    }
}