// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.CreditCard;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.CreditCard
{
    public class UpdateCreditCardCommand : IRequest<Response<bool>>
    {
        public int Id { get; set; }
        public CreditCardDto request { get; set; }

        public UpdateCreditCardCommand(int id, CreditCardDto request)
        {
            this.request = request;
            this.Id = id;
        }

        public class UpdateCreditCardHandler : IRequestHandler<UpdateCreditCardCommand, Response<bool>>
        {
            private readonly ILogger<UpdateCreditCardHandler> _logger;
            private readonly ICreditCardRepository _repository;
            public UpdateCreditCardHandler(ILogger<UpdateCreditCardHandler> logger, ICreditCardRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(UpdateCreditCardCommand request, CancellationToken cancellationToken)
            {
                var updateItem = await _repository.GetByPkAsync(request.Id);
                if (updateItem.Code == 404)
                    return Response<bool>.NotFound();
                var model = request.request;
                var returnValue = await _repository.UpdateAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}