// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Freytz.Portal.Models;
using QuickCode.Freytz.Portal.Models.MainModule;
using QuickCode.Freytz.Portal.Helpers;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.Freytz.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using MainModuleContracts = QuickCode.Freytz.Infrastructure.Integration.Nswag.Clients.MainModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.Freytz.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.Freytz.Portal.Controllers.MainModule
{
    [Permission("MainModuleShipments")]
    [Area("MainModule")]
    [Route("MainModuleShipments")]
    public partial class ShipmentsController : BaseController
    {
        private readonly MainModuleContracts.IShipmentsClient pageClient;
        private readonly MainModuleContracts.ICustomersClient pageCustomerClient;
        private readonly MainModuleContracts.IDriversClient pageDriverClient;
        private readonly MainModuleContracts.IPaymentsClient pagePaymentClient;
        private readonly MainModuleContracts.IStatesClient pageStateClient;
        private readonly MainModuleContracts.IVehicleTypesClient pageVehicleTypeClient;
        public ShipmentsController(MainModuleContracts.IShipmentsClient pageClient, MainModuleContracts.ICustomersClient pageCustomerClient, MainModuleContracts.IDriversClient pageDriverClient, MainModuleContracts.IPaymentsClient pagePaymentClient, MainModuleContracts.IStatesClient pageStateClient, MainModuleContracts.IVehicleTypesClient pageVehicleTypeClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pageCustomerClient = pageCustomerClient;
            this.pageDriverClient = pageDriverClient;
            this.pagePaymentClient = pagePaymentClient;
            this.pageStateClient = pageStateClient;
            this.pageVehicleTypeClient = pageVehicleTypeClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(ShipmentData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(ShipmentData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.ShipmentsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(ShipmentData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.ShipmentsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(ShipmentData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.ShipmentsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(ShipmentData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(ShipmentData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(ShipmentData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(ShipmentData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<ShipmentData> PrepareModel()
        {
            var model = GetModel<ShipmentData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<ShipmentData> PrepareModel(ShipmentData model)
        {
            model.NumberOfRecord = await pageClient.ShipmentsCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.ShipmentsListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("Customers", () => pageCustomerClient.CustomersListAsync()));
            comboBoxList.AddRange(await FillComboBoxAsync("Drivers", () => pageDriverClient.DriversListAsync()));
            comboBoxList.AddRange(await FillComboBoxAsync("Payments", () => pagePaymentClient.PaymentsListAsync()));
            comboBoxList.AddRange(await FillComboBoxAsync("States", () => pageStateClient.StatesListAsync()));
            comboBoxList.AddRange(await FillComboBoxAsync("VehicleTypes", () => pageVehicleTypeClient.VehicleTypesListAsync()));
            return comboBoxList;
        }
    }
}