// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.SmOtpValidation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.SmOtpValidation
{
    public class GetItemSmOtpValidationQuery : IRequest<Response<SmOtpValidationDto>>
    {
        public int Id { get; set; }

        public GetItemSmOtpValidationQuery(int id)
        {
            this.Id = id;
        }

        public class GetItemSmOtpValidationHandler : IRequestHandler<GetItemSmOtpValidationQuery, Response<SmOtpValidationDto>>
        {
            private readonly ILogger<GetItemSmOtpValidationHandler> _logger;
            private readonly ISmOtpValidationRepository _repository;
            public GetItemSmOtpValidationHandler(ILogger<GetItemSmOtpValidationHandler> logger, ISmOtpValidationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<SmOtpValidationDto>> Handle(GetItemSmOtpValidationQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.Id);
                return returnValue.ToResponse();
            }
        }
    }
}