// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.SmOtpValidation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.SmOtpValidation
{
    public class ListSmOtpValidationQuery : IRequest<Response<List<SmOtpValidationDto>>>
    {
        public int? PageNumber { get; set; }
        public int? PageSize { get; set; }

        public ListSmOtpValidationQuery(int? pageNumber, int? pageSize)
        {
            this.PageNumber = pageNumber;
            this.PageSize = pageSize;
        }

        public class ListSmOtpValidationHandler : IRequestHandler<ListSmOtpValidationQuery, Response<List<SmOtpValidationDto>>>
        {
            private readonly ILogger<ListSmOtpValidationHandler> _logger;
            private readonly ISmOtpValidationRepository _repository;
            public ListSmOtpValidationHandler(ILogger<ListSmOtpValidationHandler> logger, ISmOtpValidationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<SmOtpValidationDto>>> Handle(ListSmOtpValidationQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.ListAsync(request.PageNumber, request.PageSize);
                return returnValue.ToResponse();
            }
        }
    }
}