-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT SO.[ID], SO.[GSM_NUMBER], SO.[SMS_CODE], SO.[SMS_DATE], SO.[SMS_VALID_SECOND] 
FROM [SMS_OTPS] SO 
WHERE SO.[IsDeleted] = 0 
	AND SO.[SMS_DATE] > DATEADD(HOUR, -1,
	GETDATE()) 
ORDER BY SO.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 