// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Freytz.MainModule.Application.Dtos.CreditCard;
using CreditCardEntity = QuickCode.Freytz.MainModule.Domain.Entities.CreditCard;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Mappings
{
    public static class CreditCardMappings
    {
        public static List<CreditCardDto> ToDto(this IEnumerable<CreditCardEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CreditCardDto ToDto(this CreditCardEntity model)
        {
            return new CreditCardDto
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                CcOwnerName = model.CcOwnerName,
                CcCardNo = model.CcCardNo,
                CcValidDate = model.CcValidDate,
                CcCvc = model.CcCvc,
                CcSecurityKey = model.CcSecurityKey,
                IsStored = model.IsStored
            };
        }

        public static CreditCardEntity ToEntity(this CreditCardDto model)
        {
            return new CreditCardEntity
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                CcOwnerName = model.CcOwnerName,
                CcCardNo = model.CcCardNo,
                CcValidDate = model.CcValidDate,
                CcCvc = model.CcCvc,
                CcSecurityKey = model.CcSecurityKey,
                IsStored = model.IsStored
            };
        }
    }
}