// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Freytz.MainModule.Application.Dtos.SmInfo;
using SmInfoEntity = QuickCode.Freytz.MainModule.Domain.Entities.SmInfo;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Mappings
{
    public static class SmInfoMappings
    {
        public static List<SmInfoDto> ToDto(this IEnumerable<SmInfoEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static SmInfoDto ToDto(this SmInfoEntity model)
        {
            return new SmInfoDto
            {
                Id = model.Id,
                GsmNumber = model.GsmNumber,
                Message = model.Message,
                SmsDate = model.SmsDate,
                MessageSid = model.MessageSid
            };
        }

        public static SmInfoEntity ToEntity(this SmInfoDto model)
        {
            return new SmInfoEntity
            {
                Id = model.Id,
                GsmNumber = model.GsmNumber,
                Message = model.Message,
                SmsDate = model.SmsDate,
                MessageSid = model.MessageSid
            };
        }
    }
}