// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Freytz.MainModule.Application.Dtos.UserState;
using UserStateEntity = QuickCode.Freytz.MainModule.Domain.Entities.UserState;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Mappings
{
    public static class UserStateMappings
    {
        public static List<UserStateDto> ToDto(this IEnumerable<UserStateEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static UserStateDto ToDto(this UserStateEntity model)
        {
            return new UserStateDto
            {
                StateId = model.StateId,
                UserId = model.UserId
            };
        }

        public static UserStateEntity ToEntity(this UserStateDto model)
        {
            return new UserStateEntity
            {
                StateId = model.StateId,
                UserId = model.UserId
            };
        }
    }
}