-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [STATE_ID],
    [USER_ID]
FROM [dbo].[USER_STATES]
WHERE EXISTS (
    SELECT 1
    FROM [dbo].[STATES] qc_sd_p
    WHERE qc_sd_p.[ID] = [dbo].[USER_STATES].[STATE_ID]
      AND qc_sd_p.[IsDeleted] = 0)
ORDER BY
    [STATE_ID],
    [USER_ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;