// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.SmOtpValidation;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.SmOtpValidation
{
    public class IncrementTryCommand : IRequest<Response<int>>
    {
        public int SmOtpValidationId { get; set; }
        public IncrementTryRequestDto UpdateRequest { get; set; }

        public IncrementTryCommand(int smOtpValidationId, IncrementTryRequestDto updateRequest)
        {
            this.SmOtpValidationId = smOtpValidationId;
            this.UpdateRequest = updateRequest;
        }

        public class IncrementTryHandler : IRequestHandler<IncrementTryCommand, Response<int>>
        {
            private readonly ILogger<IncrementTryHandler> _logger;
            private readonly ISmOtpValidationRepository _repository;
            public IncrementTryHandler(ILogger<IncrementTryHandler> logger, ISmOtpValidationRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(IncrementTryCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.IncrementTryAsync(request.SmOtpValidationId, request.UpdateRequest);
                return returnValue.ToResponse();
            }
        }
    }
}