// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.MainModule.Domain.Entities;
using QuickCode.Freytz.MainModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.MainModule.Application.Dtos.DriverCommission;
using QuickCode.Freytz.MainModule.Domain.Enums;

namespace QuickCode.Freytz.MainModule.Application.Features.DriverCommission
{
    public class InsertDriverCommissionCommand : IRequest<Response<DriverCommissionDto>>
    {
        public DriverCommissionDto request { get; set; }

        public InsertDriverCommissionCommand(DriverCommissionDto request)
        {
            this.request = request;
        }

        public class InsertDriverCommissionHandler : IRequestHandler<InsertDriverCommissionCommand, Response<DriverCommissionDto>>
        {
            private readonly ILogger<InsertDriverCommissionHandler> _logger;
            private readonly IDriverCommissionRepository _repository;
            public InsertDriverCommissionHandler(ILogger<InsertDriverCommissionHandler> logger, IDriverCommissionRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<DriverCommissionDto>> Handle(InsertDriverCommissionCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.InsertAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}