// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Freytz.Infrastructure.Integration.Nswag.Clients.MainModuleApi.Contracts;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Freytz.Portal.Helpers;

namespace QuickCode.Freytz.Portal.Models.MainModule
{
    public class CreditCardData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public string SelectedKey { get; set; }
        public CreditCardDto SelectedItem { get; set; }
        public List<CreditCardDto> List { get; set; }
    }

    public static partial class CreditCardExtensions
    {
        public static string GetKey(this CreditCardDto dto)
        {
            return $"{dto.Id}";
        }
    }
}