// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Freytz.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Freytz.Application.Contracts;
using QuickCode.Freytz.IdentityModule.Domain.Entities;
using QuickCode.Freytz.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.Freytz.IdentityModule.Application.Dtos.KafkaEvent;
using QuickCode.Freytz.IdentityModule.Domain.Enums;

namespace QuickCode.Freytz.IdentityModule.Application.Features.KafkaEvent
{
    public class GetTopicWorkflowsKafkaEventsQuery : IRequest<Response<List<GetTopicWorkflowsKafkaEventsResponseDto>>>
    {
        public string KafkaEventsTopicName { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetTopicWorkflowsKafkaEventsQuery(string kafkaEventsTopicName, int? pageNumber, int? pageSize)
        {
            this.KafkaEventsTopicName = kafkaEventsTopicName;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetTopicWorkflowsKafkaEventsHandler : IRequestHandler<GetTopicWorkflowsKafkaEventsQuery, Response<List<GetTopicWorkflowsKafkaEventsResponseDto>>>
        {
            private readonly ILogger<GetTopicWorkflowsKafkaEventsHandler> _logger;
            private readonly IKafkaEventRepository _repository;
            public GetTopicWorkflowsKafkaEventsHandler(ILogger<GetTopicWorkflowsKafkaEventsHandler> logger, IKafkaEventRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetTopicWorkflowsKafkaEventsResponseDto>>> Handle(GetTopicWorkflowsKafkaEventsQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetTopicWorkflowsKafkaEventsAsync(request.KafkaEventsTopicName, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}